//! Generated by `scripts/gen_api_ontology.py`. Do not edit.
//!
//! Imports every type the authoring ontology describes, at the path it
//! publishes. If this stops compiling, the ontology is telling agents to
//! write an import that does not resolve.

#![allow(unused_imports)]

use hawktui::agent::driver::HeadlessDriver;
use hawktui::agent::session::AgentSession;
use hawktui::backend::test::TestBackend;
use hawktui::backend::Backend;
use hawktui::core::buffer::Buffer;
use hawktui::core::cell::Cell;
use hawktui::core::rect::Rect;
use hawktui::core::style::Color;
use hawktui::core::style::Style;
use hawktui::core::style::Stylize;
use hawktui::core::symbol::Symbol;
use hawktui::core::text::Alignment;
use hawktui::core::text::Line;
use hawktui::core::text::Span;
use hawktui::core::text::Text;
use hawktui::event::Event;
use hawktui::event::HitMap;
use hawktui::event::KeyCode;
use hawktui::event::KeyEvent;
use hawktui::event::KeyEventKind;
use hawktui::event::MouseButton;
use hawktui::event::MouseEvent;
use hawktui::event::MouseEventKind;
use hawktui::focus::FocusManager;
use hawktui::layout::Constraint;
use hawktui::layout::Direction;
use hawktui::layout::Flex;
use hawktui::layout::Layout;
use hawktui::overlay::ModalBox;
use hawktui::overlay::OverlayStack;
use hawktui::runtime::Command;
use hawktui::runtime::Model;
use hawktui::runtime::Program;
use hawktui::terminal::Frame;
use hawktui::terminal::Terminal;
use hawktui::testing::Harness;
use hawktui::widget::barchart::Bar;
use hawktui::widget::barchart::BarChart;
use hawktui::widget::barchart::BarDirection;
use hawktui::widget::barchart::BarGroup;
use hawktui::widget::block::Block;
use hawktui::widget::block::BorderType;
use hawktui::widget::calendar::Calendar;
use hawktui::widget::cancellable_loader::CancellableLoader;
use hawktui::widget::canvas::BrailleGrid;
use hawktui::widget::canvas::Canvas;
use hawktui::widget::canvas::CanvasMap;
use hawktui::widget::canvas::MapData;
use hawktui::widget::canvas::MapResolution;
use hawktui::widget::canvas::Painter;
use hawktui::widget::canvas::Shape;
use hawktui::widget::chart::Axis;
use hawktui::widget::chart::Chart;
use hawktui::widget::chart::Dataset;
use hawktui::widget::chart::GraphType;
use hawktui::widget::chart::LegendPosition;
use hawktui::widget::chart::Marker;
use hawktui::widget::editor::Editor;
use hawktui::widget::editor::EditorState;
use hawktui::widget::gauge::Gauge;
use hawktui::widget::image::Image;
use hawktui::widget::image::ImageProtocol;
use hawktui::widget::image::Pixels;
use hawktui::widget::input::Input;
use hawktui::widget::input::InputState;
use hawktui::widget::line_gauge::LineGauge;
use hawktui::widget::list::List;
use hawktui::widget::list::ListDirection;
use hawktui::widget::list::ListItem;
use hawktui::widget::list::ListState;
use hawktui::widget::loader::Loader;
use hawktui::widget::loader::SpinnerStyle;
use hawktui::widget::markdown::Markdown;
use hawktui::widget::paragraph::Paragraph;
use hawktui::widget::paragraph::Wrap;
use hawktui::widget::scrollbar::Scrollbar;
use hawktui::widget::scrollbar::ScrollbarOrientation;
use hawktui::widget::scrollbar::ScrollbarState;
use hawktui::widget::select_list::SelectItem;
use hawktui::widget::select_list::SelectList;
use hawktui::widget::select_list::SelectListState;
use hawktui::widget::select_list::SelectMode;
use hawktui::widget::settings_list::Setting;
use hawktui::widget::settings_list::SettingsList;
use hawktui::widget::settings_list::SettingsListState;
use hawktui::widget::sparkline::Sparkline;
use hawktui::widget::sparkline::SparklineDirection;
use hawktui::widget::table::Table;
use hawktui::widget::table::TableColumn;
use hawktui::widget::table::TableColumnWidth;
use hawktui::widget::table::TableRow;
use hawktui::widget::table::TableState;
use hawktui::widget::tabs::Tabs;

fn main() {}
