#!/usr/bin/env python3
"""Put the widget ontology in the source, where an agent already looks.

The ontology has always been *derived* from the source, but it lived in an
`impl Discoverable` block hundreds of lines below the type it describes, and
nowhere in the rendered docs. Agents read the framework's source in 100% of runs
and reach it by turn 3; they consult a separately delivered ontology in 22-89%
of runs depending on how it is served, and eight grids found no outcome
difference from serving it at all. So the cheapest place to put semantics is the
doc comment of the type itself, which is what the reader was going to open.

This writes a delimited block into each widget's doc comment, generated from the
same registry that backs `ontology_query`. One source of truth, two renderings.

    python scripts/gen_widget_docs.py            # rewrite the blocks
    python scripts/gen_widget_docs.py --check    # fail if any is stale

`tests/widget_doc_tests.rs` runs --check, so drift breaks the build.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
START = "/// <!-- ontology:start -->"
END = "/// <!-- ontology:end -->"


def ontology() -> dict:
    proc = subprocess.run(
        ["cargo", "run", "--quiet", "--example", "ontology_query", "--", "export"],
        cwd=REPO, capture_output=True, text=True, encoding="utf-8", errors="replace",
    )
    if proc.returncode != 0:
        sys.exit(f"ontology_query export failed:\n{proc.stderr}")
    return json.loads(proc.stdout)


def constraint_text(cs: list) -> str:
    out = []
    for c in cs or []:
        if isinstance(c, dict):
            for k, v in c.items():
                out.append(f"{k.lower()} {v}")
        else:
            out.append(str(c))
    return ", ".join(out)


def type_text(t) -> str:
    if isinstance(t, dict):
        for k, v in t.items():
            if k == "Enum":
                return " | ".join(v)
            return f"{k}({v})" if v else k
        return "?"
    return str(t)


def block(schema: dict) -> list[str]:
    """The generated doc lines, without a trailing newline on the last."""
    role = schema.get("default_role") or "—"
    tags = ", ".join(f"`{t}`" for t in schema.get("tags") or []) or "—"
    lines = [START, "///", f"/// **Ontology** — role `{role}`, tags {tags}.", "///"]

    props = schema.get("properties") or []
    if props:
        lines.append("/// | property | type | required | default | constraints |")
        lines.append("/// |---|---|---|---|---|")
        for p in props:
            cons = constraint_text(p.get("constraints")) or "—"
            dv = p.get("default_value")
            dv = "—" if dv is None else f"`{json.dumps(dv)}`"
            lines.append(
                f"/// | `{p['name']}` | {type_text(p.get('property_type'))} | "
                f"{'yes' if p.get('required') else 'no'} | {dv} | {cons} |"
            )
        lines.append("///")

    actions = schema.get("actions") or []
    if actions:
        for a in actions:
            params = ", ".join(
                f"{q['name']}: {type_text(q.get('param_type'))}" for q in a.get("params") or []
            )
            flags = []
            if a.get("mutates"):
                flags.append("mutates")
            if a.get("idempotent"):
                flags.append("idempotent")
            suffix = f" _({', '.join(flags)})_" if flags else ""
            # `returns` is prose describing the value, not a type, so it reads
            # as a sentence rather than as a signature arrow.
            ret = a.get("returns")
            tail = f" {a.get('description','')}".rstrip()
            if ret:
                tail += f" Returns {ret[0].lower() + ret[1:] if ret else ret}"
            lines.append(f"/// - action `{a['name']}({params})`{suffix} —{tail}")
        lines.append("///")

    hint = schema.get("usage_hint")
    if hint:
        lines.append(f"/// Usage: {hint}")
        lines.append("///")

    lines.append("/// _Generated by `scripts/gen_widget_docs.py` from the widget"
                 " registry; edit the `Discoverable` impl, not this block._")
    lines.append(END)
    return lines


def doc_insertion_point(src: list[str], struct_line: int) -> tuple[int, int]:
    """Where the type's doc comment ends, and where an existing block starts.

    Walks up from `pub struct X` past attributes to the contiguous `///` run.
    Returns (insert_at, replace_from) with replace_from == -1 when absent.
    """
    i = struct_line - 1
    while i >= 0 and (src[i].lstrip().startswith("#[") or not src[i].strip()):
        i -= 1
    end_of_docs = i + 1
    start = i
    while start >= 0 and src[start].lstrip().startswith("///"):
        start -= 1
    start += 1
    for n in range(start, end_of_docs):
        if src[n].strip() == START:
            return n, n
    return end_of_docs, -1


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="exit non-zero if any block is missing or stale")
    args = ap.parse_args()

    schemas = ontology()
    stale, written = [], 0
    for name, schema in sorted(schemas.items()):
        hits = [p for p in (REPO / "src").rglob("*.rs")
                if re.search(rf"^pub struct {name}\b", p.read_text(encoding="utf-8"), re.M)]
        if len(hits) != 1:
            sys.exit(f"{name}: expected exactly one declaring file, found {len(hits)}")
        path = hits[0]
        src = path.read_text(encoding="utf-8").split("\n")
        line = next(n for n, l in enumerate(src)
                    if re.match(rf"^pub struct {name}\b", l))
        insert_at, replace_from = doc_insertion_point(src, line)

        new = block(schema)
        if replace_from >= 0:
            end = next(n for n in range(replace_from, len(src)) if src[n].strip() == END)
            current = src[replace_from:end + 1]
            if current == new:
                continue
            if args.check:
                stale.append(name)
                continue
            src[replace_from:end + 1] = new
        else:
            if args.check:
                stale.append(name)
                continue
            src[insert_at:insert_at] = new
        path.write_text("\n".join(src), encoding="utf-8")
        written += 1

    if args.check:
        if stale:
            print("widget doc ontology is stale for: " + ", ".join(stale))
            print("run: python scripts/gen_widget_docs.py")
            return 1
        print(f"widget doc ontology in sync: {len(schemas)} widgets")
        return 0
    print(f"wrote {written} of {len(schemas)} widget doc blocks")
    return 0


if __name__ == "__main__":
    sys.exit(main())
