#!/usr/bin/env python3
"""Put the import map in the crate docs, where an agent lands first.

An unresolved path is the single most common compile error agents hit against
this crate: 30 of 61 API errors in one nine-run grid, 41 of 68 in another, and
the one class every ontology delivery reduces. It is not a reasoning failure.
The agent knows it wants a `Gauge` and guesses where `Gauge` lives.

The answer already exists as the `module` field of every entry in
`src/ontology/api_generated.rs`. This copies it into the crate-level doc comment
in `src/lib.rs`, which is the first file anyone opens and the first thing
rustdoc renders, and emits `tests/import_map_tests.rs` so that every path in the
map is compiled. A map with a wrong path would hand a reader the exact error it
exists to prevent, and compiling them is the only check that cannot be fooled.

    python scripts/gen_api_map.py            # rewrite both
    python scripts/gen_api_map.py --check    # fail if either is stale

Reads the generated file directly rather than building the crate, so the
staleness check stays fast.
"""

from __future__ import annotations

import argparse
import re
import sys
from collections import defaultdict
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
GENERATED = REPO / "src" / "ontology" / "api_generated.rs"
LIB = REPO / "src" / "lib.rs"
IMPORT_TEST = REPO / "tests" / "import_map_tests.rs"
START = "//! <!-- api-map:start -->"
END = "//! <!-- api-map:end -->"
HEADER_LINES = 13

ENTRY = re.compile(
    r'ApiType\s*\{\s*name:\s*"(?P<name>[^"]+)",\s*'
    r'module:\s*"(?P<module>[^"]+)",\s*'
    r'kind:\s*ApiKind::(?P<kind>\w+)',
    re.S,
)

NL = chr(10)


def entries() -> list[tuple[str, str, str]]:
    src = GENERATED.read_text(encoding="utf-8")
    found = [(m["name"], m["module"], m["kind"]) for m in ENTRY.finditer(src)]
    if not found:
        sys.exit("no ApiType entries parsed; has api_generated.rs changed shape?")
    return found


def block() -> list[str]:
    by_module: dict[str, list[str]] = defaultdict(list)
    for name, module, _kind in entries():
        by_module[module].append(name)
    total = sum(len(v) for v in by_module.values())
    lines = [
        START,
        "//!",
        "//! ## Import map",
        "//!",
        f"//! Every public type in the crate ({total} of them) and the path it is",
        "//! imported from. An unresolved path is the most common compile error",
        "//! against this crate, and it is a lookup rather than a reasoning",
        "//! problem, so the lookup lives here.",
        "//!",
        "//! | import from | types |",
        "//! |---|---|",
    ]
    for module in sorted(by_module):
        names = ", ".join(f"`{n}`" for n in sorted(by_module[module]))
        lines.append(f"//! | `{module}` | {names} |")
    lines += [
        "//!",
        "//! _Generated by `scripts/gen_api_map.py` from"
        " `src/ontology/api_generated.rs`; do not edit by hand._",
        END,
    ]
    return lines


def import_test() -> str:
    uses = NL.join(
        f"    #[allow(unused_imports)]{NL}    use {module}::{name};"
        for name, module, _ in sorted(entries())
    )
    head = [
        "//! Every path in the import map in `src/lib.rs` must actually import.",
        "//!",
        "//! Generated by `scripts/gen_api_map.py`; do not edit by hand. A failure",
        "//! here means the map would hand a reader an unresolved path, which is",
        "//! the error it exists to prevent.",
        "",
        "#[test]",
        "fn every_mapped_path_resolves() {",
    ]
    return NL.join(head) + NL + uses + NL + "}" + NL


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    src = LIB.read_text(encoding="utf-8").split(NL)
    new = block()
    try:
        lo = next(i for i, l in enumerate(src) if l.strip() == START)
        hi = next(i for i, l in enumerate(src) if l.strip() == END)
        current = src[lo:hi + 1]
    except StopIteration:
        lo = hi = None
        current = None

    want_test = import_test()
    have_test = IMPORT_TEST.read_text(encoding="utf-8") if IMPORT_TEST.is_file() else None

    if current == new and have_test == want_test:
        if args.check:
            print(f"import map in sync: {len(new) - HEADER_LINES} modules")
        return 0
    if args.check:
        print("import map in src/lib.rs or tests/import_map_tests.rs is stale")
        print("run: python scripts/gen_api_map.py")
        return 1

    if have_test != want_test:
        IMPORT_TEST.write_text(want_test, encoding="utf-8")
    if current != new:
        if lo is None:
            end_of_docs = max(i for i, l in enumerate(src)
                              if l.startswith("//!") and i < 400) + 1
            src[end_of_docs:end_of_docs] = new
        else:
            src[lo:hi + 1] = new
        LIB.write_text(NL.join(src), encoding="utf-8")
    print(f"wrote the import map: {len(new) - HEADER_LINES} modules, "
          f"{len(entries())} paths under test")
    return 0


if __name__ == "__main__":
    sys.exit(main())
