//! The authoring API, generated from the source by
//! `scripts/gen_api_ontology.py`. Do not edit by hand.
//!
//! Regenerate with `python scripts/gen_api_ontology.py`;
//! `tests/api_ontology_tests.rs` fails when this is stale.

use super::api::{ApiFn, ApiKind, ApiType};

/// Every public type an author builds a program out of (90 of them).
pub static API: &[ApiType] = &[
    ApiType {
        name: "Alignment",
        module: "hawktui::core",
        kind: ApiKind::Enum,
        summary: "Text alignment within a line.",
        variants: &["Left", "Center", "Right"],
        functions: &[
        ],
    },
    ApiType {
        name: "Axis",
        module: "hawktui::widget::chart",
        kind: ApiKind::Struct,
        summary: "An axis on the chart.",
        variants: &[],
        functions: &[
            ApiFn { name: "new", signature: "pub fn new(bounds: [f64; 2]) -> Self", role: "constructor", summary: "" },
            ApiFn { name: "title", signature: "pub fn title(mut self, title: impl Into<Span>) -> Self", role: "builder", summary: "" },
            ApiFn { name: "labels", signature: "pub fn labels(mut self, labels: impl Into<Vec<Span>>) -> Self", role: "builder", summary: "" },
            ApiFn { name: "style", signature: "pub fn style(mut self, style: Style) -> Self", role: "builder", summary: "" },
        ],
    },
    ApiType {
        name: "Backend",
        module: "hawktui::backend",
        kind: ApiKind::Trait,
        summary: "Trait for terminal backends.",
        variants: &[],
        functions: &[
            ApiFn { name: "draw", signature: "fn draw<'a, I>(&mut self, content: I) -> io::Result<()> where I: Iterator<Item = (u16, u16, &'a Cell)>", role: "required", summary: "" },
            ApiFn { name: "draw_linked", signature: "fn draw_linked<'a, I>(&mut self, content: I) -> io::Result<()> where I: Iterator<Item = (u16, u16, &'a Cell, Option<&'a str>)>,", role: "required", summary: "" },
            ApiFn { name: "hide_cursor", signature: "fn hide_cursor(&mut self) -> io::Result<()>", role: "required", summary: "" },
            ApiFn { name: "show_cursor", signature: "fn show_cursor(&mut self) -> io::Result<()>", role: "required", summary: "" },
            ApiFn { name: "set_cursor_position", signature: "fn set_cursor_position(&mut self, position: Position) -> io::Result<()>", role: "required", summary: "" },
            ApiFn { name: "get_cursor_position", signature: "fn get_cursor_position(&mut self) -> io::Result<Position>", role: "required", summary: "" },
            ApiFn { name: "clear", signature: "fn clear(&mut self) -> io::Result<()>", role: "required", summary: "" },
            ApiFn { name: "size", signature: "fn size(&self) -> io::Result<Size>", role: "required", summary: "" },
            ApiFn { name: "flush", signature: "fn flush(&mut self) -> io::Result<()>", role: "required", summary: "" },
            ApiFn { name: "enable_mouse_capture", signature: "fn enable_mouse_capture(&mut self) -> io::Result<()>", role: "required", summary: "" },
            ApiFn { name: "disable_mouse_capture", signature: "fn disable_mouse_capture(&mut self) -> io::Result<()>", role: "required", summary: "" },
            ApiFn { name: "enter_alternate_screen", signature: "fn enter_alternate_screen(&mut self) -> io::Result<()>", role: "required", summary: "" },
            ApiFn { name: "leave_alternate_screen", signature: "fn leave_alternate_screen(&mut self) -> io::Result<()>", role: "required", summary: "" },
            ApiFn { name: "enable_raw_mode", signature: "fn enable_raw_mode(&mut self) -> io::Result<()>", role: "required", summary: "" },
            ApiFn { name: "disable_raw_mode", signature: "fn disable_raw_mode(&mut self) -> io::Result<()>", role: "required", summary: "" },
            ApiFn { name: "enable_bracketed_paste", signature: "fn enable_bracketed_paste(&mut self) -> io::Result<()>", role: "provided", summary: "" },
            ApiFn { name: "disable_bracketed_paste", signature: "fn disable_bracketed_paste(&mut self) -> io::Result<()>", role: "provided", summary: "" },
            ApiFn { name: "begin_sync", signature: "fn begin_sync(&mut self) -> io::Result<()>", role: "provided", summary: "" },
            ApiFn { name: "end_sync", signature: "fn end_sync(&mut self) -> io::Result<()>", role: "provided", summary: "" },
        ],
    },
    ApiType {
        name: "Bar",
        module: "hawktui::widget::barchart",
        kind: ApiKind::Struct,
        summary: "A single bar in a bar chart.",
        variants: &[],
        functions: &[
            ApiFn { name: "new", signature: "pub fn new(value: u64) -> Self", role: "constructor", summary: "" },
            ApiFn { name: "label", signature: "pub fn label(mut self, label: impl Into<Span>) -> Self", role: "builder", summary: "" },
            ApiFn { name: "style", signature: "pub fn style(mut self, style: Style) -> Self", role: "builder", summary: "" },
            ApiFn { name: "value_style", signature: "pub fn value_style(mut self, style: Style) -> Self", role: "builder", summary: "" },
        ],
    },
    ApiType {
        name: "BarChart",
        module: "hawktui::widget::barchart",
        kind: ApiKind::Widget,
        summary: "Bar chart widget for visualizing categorical data.",
        variants: &[],
        functions: &[
            ApiFn { name: "new", signature: "pub fn new(groups: impl Into<Vec<BarGroup>>) -> Self", role: "constructor", summary: "" },
            ApiFn { name: "block", signature: "pub fn block(mut self, block: Block) -> Self", role: "builder", summary: "" },
            ApiFn { name: "style", signature: "pub fn style(mut self, style: Style) -> Self", role: "builder", summary: "" },
            ApiFn { name: "bar_width", signature: "pub fn bar_width(mut self, width: u16) -> Self", role: "builder", summary: "Width of each bar in terminal columns." },
            ApiFn { name: "bar_gap", signature: "pub fn bar_gap(mut self, gap: u16) -> Self", role: "builder", summary: "Gap between bars within a group." },
            ApiFn { name: "group_gap", signature: "pub fn group_gap(mut self, gap: u16) -> Self", role: "builder", summary: "Gap between groups." },
            ApiFn { name: "max_value", signature: "pub fn max_value(mut self, max: u64) -> Self", role: "builder", summary: "Manually set the maximum value. If `None`, auto-detects from data." },
            ApiFn { name: "direction", signature: "pub fn direction(mut self, direction: BarDirection) -> Self", role: "builder", summary: "Set bar direction (vertical or horizontal)." },
            ApiFn { name: "value_style", signature: "pub fn value_style(mut self, style: Style) -> Self", role: "builder", summary: "Style for value labels displayed alongside bars." },
            ApiFn { name: "label_style", signature: "pub fn label_style(mut self, style: Style) -> Self", role: "builder", summary: "Style for bar/group labels." },
        ],
    },
    ApiType {
        name: "BarDirection",
        module: "hawktui::widget::barchart",
        kind: ApiKind::Enum,
        summary: "Direction for bar rendering.",
        variants: &["Vertical", "Horizontal"],
        functions: &[
        ],
    },
    ApiType {
        name: "BarGroup",
        module: "hawktui::widget::barchart",
        kind: ApiKind::Struct,
        summary: "A group of bars rendered side-by-side with an optional group label.",
        variants: &[],
        functions: &[
            ApiFn { name: "new", signature: "pub fn new(bars: impl Into<Vec<Bar>>) -> Self", role: "constructor", summary: "" },
            ApiFn { name: "label", signature: "pub fn label(mut self, label: impl Into<Span>) -> Self", role: "builder", summary: "" },
        ],
    },
    ApiType {
        name: "Block",
        module: "hawktui::widget::block",
        kind: ApiKind::Widget,
        summary: "A container widget that draws borders, titles, and background.",
        variants: &[],
        functions: &[
            ApiFn { name: "new", signature: "pub fn new() -> Self", role: "constructor", summary: "" },
            ApiFn { name: "bordered", signature: "pub fn bordered() -> Self", role: "constructor", summary: "" },
            ApiFn { name: "title", signature: "pub fn title(mut self, title: impl Into<Line>) -> Self", role: "builder", summary: "" },
            ApiFn { name: "title_bottom", signature: "pub fn title_bottom(mut self, title: impl Into<Line>) -> Self", role: "builder", summary: "" },
            ApiFn { name: "title_alignment", signature: "pub fn title_alignment(mut self, alignment: Alignment) -> Self", role: "builder", summary: "" },
            ApiFn { name: "title_bottom_alignment", signature: "pub fn title_bottom_alignment(mut self, alignment: Alignment) -> Self", role: "builder", summary: "" },
            ApiFn { name: "borders", signature: "pub fn borders(mut self, borders: Borders) -> Self", role: "builder", summary: "" },
            ApiFn { name: "border_type", signature: "pub fn border_type(mut self, border_type: BorderType) -> Self", role: "builder", summary: "" },
            ApiFn { name: "border_style", signature: "pub fn border_style(mut self, style: Style) -> Self", role: "builder", summary: "" },
            ApiFn { name: "style", signature: "pub fn style(mut self, style: Style) -> Self", role: "builder", summary: "" },
            ApiFn { name: "padding", signature: "pub fn padding(mut self, padding: Margin) -> Self", role: "builder", summary: "" },
            ApiFn { name: "inner", signature: "pub fn inner(&self, area: Rect) -> Rect", role: "method", summary: "Calculate the inner area after borders and padding." },
        ],
    },
    ApiType {
        name: "BorderType",
        module: "hawktui::widget::block",
        kind: ApiKind::Enum,
        summary: "Border type for blocks.",
        variants: &["Plain", "Rounded", "Double", "Thick", "QuadrantInside", "QuadrantOutside"],
        functions: &[
        ],
    },
    ApiType {
        name: "BrailleGrid",
        module: "hawktui::widget::canvas",
        kind: ApiKind::Struct,
        summary: "Braille dot grid for sub-cell resolution rendering.",
        variants: &[],
        functions: &[
            ApiFn { name: "new", signature: "pub fn new(width: usize, height: usize) -> Self", role: "constructor", summary: "" },
            ApiFn { name: "set", signature: "pub fn set(&mut self, x: usize, y: usize, color: Color)", role: "method", summary: "" },
            ApiFn { name: "render_cell", signature: "pub fn render_cell(&self, cx: usize, cy: usize) -> (char, Color)", role: "method", summary: "" },
        ],
    },
    ApiType {
        name: "Buffer",
        module: "hawktui::core",
        kind: ApiKind::Struct,
        summary: "A two-dimensional grid of terminal cells.",
        variants: &[],
        functions: &[
            ApiFn { name: "empty", signature: "pub fn empty(area: Rect) -> Self", role: "constructor", summary: "Create a new buffer filled with empty cells." },
            ApiFn { name: "with_lines", signature: "pub fn with_lines<'a>(lines: impl IntoIterator<Item = &'a str>) -> Self", role: "constructor", summary: "Create a buffer filled with a specific string (for testing)." },
            ApiFn { name: "reset", signature: "pub fn reset(&mut self)", role: "method", summary: "Reset all cells to empty." },
            ApiFn { name: "resize", signature: "pub fn resize(&mut self, area: Rect)", role: "method", summary: "Resize the buffer (discards content)." },
            ApiFn { name: "cell", signature: "pub fn cell(&self, pos: Position) -> Option<&Cell>", role: "method", summary: "Get the cell at (x, y), if within bounds." },
            ApiFn { name: "cell_mut", signature: "pub fn cell_mut(&mut self, pos: Position) -> Option<&mut Cell>", role: "method", summary: "Get a mutable reference to the cell at (x, y)." },
            ApiFn { name: "row_text", signature: "pub fn row_text(&self, y: u16) -> String", role: "method", summary: "The text of one row, without styling." },
            ApiFn { name: "to_text", signature: "pub fn to_text(&self) -> String", role: "method", summary: "The whole buffer as plain text, one line per row, joined by `\\n`." },
            ApiFn { name: "set_string", signature: "pub fn set_string(&mut self, x: u16, y: u16, string: &str, style: Style) -> u16", role: "method", summary: "Set a string starting at (x, y) with the given style." },
            ApiFn { name: "set_string_truncated", signature: "pub fn set_string_truncated( &mut self, x: u16, y: u16, string: &str, max_width: u16, style: Style, ) -> u16", role: "method", summary: "Set a string with a maximum width, truncating if necessary." },
            ApiFn { name: "set_grapheme", signature: "pub fn set_grapheme(&mut self, x: u16, y: u16, symbol: &str, style: Style) -> u16", role: "method", summary: "Write one grapheme at `(x, y)`, returning the columns it consumed." },
            ApiFn { name: "set_symbol", signature: "pub fn set_symbol(&mut self, x: u16, y: u16, symbol: Symbol, style: Style) -> u16", role: "method", summary: "Write an already-converted [`Symbol`] at `(x, y)`." },
            ApiFn { name: "set_line", signature: "pub fn set_line(&mut self, x: u16, y: u16, line: &Line, max_width: u16) -> u16", role: "method", summary: "Set a styled line at position." },
            ApiFn { name: "set_span", signature: "pub fn set_span(&mut self, x: u16, y: u16, span: &Span, max_width: u16) -> u16", role: "method", summary: "Set a single span at position with a maximum width." },
            ApiFn { name: "set_style", signature: "pub fn set_style(&mut self, area: Rect, style: Style)", role: "method", summary: "Fill an area with a style (without changing symbols)." },
            ApiFn { name: "fill", signature: "pub fn fill(&mut self, area: Rect, symbol: &str, style: Style)", role: "method", summary: "Fill an area with a character and style." },
            ApiFn { name: "set_hyperlink", signature: "pub fn set_hyperlink(&mut self, x: u16, y: u16, width: u16, url: &str)", role: "method", summary: "Attach a hyperlink to the cells `[x, x + width)` of row `y`." },
            ApiFn { name: "set_string_linked", signature: "pub fn set_string_linked( &mut self, x: u16, y: u16, string: &str, style: Style, url: &str, ) -> u16", role: "method", summary: "Write a string and make it a hyperlink in one step." },
            ApiFn { name: "hyperlink_at", signature: "pub fn hyperlink_at(&self, x: u16, y: u16) -> Option<&str>", role: "method", summary: "The hyperlink attached to the cell at `(x, y)`, if any." },
            ApiFn { name: "attach_hyperlinks", signature: "pub fn attach_hyperlinks<'a>( &'a self, changes: &[(u16, u16, &'a Cell)], ) -> Vec<(u16, u16, &'a Cell, Option<&'a str>)>", role: "method", summary: "Pair each changed cell with the hyperlink covering it, for the backend." },
            ApiFn { name: "clear_hyperlinks", signature: "pub fn clear_hyperlinks(&mut self)", role: "method", summary: "Remove every hyperlink in this buffer." },
            ApiFn { name: "has_hyperlinks", signature: "pub fn has_hyperlinks(&self) -> bool", role: "method", summary: "Whether any cell in this buffer carries a hyperlink." },
            ApiFn { name: "diff", signature: "pub fn diff<'a>(&'a self, other: &'a Buffer) -> Vec<(u16, u16, &'a Cell)>", role: "method", summary: "Compute the diff between this buffer and another." },
            ApiFn { name: "merge", signature: "pub fn merge(&mut self, other: &Buffer)", role: "method", summary: "Merge another buffer on top of this one at its area position." },
        ],
    },
    ApiType {
        name: "Calendar",
        module: "hawktui::widget::calendar",
        kind: ApiKind::Widget,
        summary: "A month-view calendar widget.",
        variants: &[],
        functions: &[
            ApiFn { name: "new", signature: "pub fn new(year: i32, month: u32) -> Self", role: "constructor", summary: "Create a new calendar for the given year and month (1-12)." },
            ApiFn { name: "block", signature: "pub fn block(mut self, block: Block) -> Self", role: "builder", summary: "" },
            ApiFn { name: "style", signature: "pub fn style(mut self, style: Style) -> Self", role: "builder", summary: "" },
            ApiFn { name: "header_style", signature: "pub fn header_style(mut self, style: Style) -> Self", role: "builder", summary: "" },
            ApiFn { name: "show_header", signature: "pub fn show_header(mut self, show: bool) -> Self", role: "builder", summary: "" },
            ApiFn { name: "highlight_day", signature: "pub fn highlight_day(mut self, day: u32, style: Style) -> Self", role: "builder", summary: "Highlight a specific day with a style." },
            ApiFn { name: "highlight_today", signature: "pub fn highlight_today(mut self, style: Style) -> Self", role: "builder", summary: "" },
        ],
    },
    ApiType {
        name: "CancellableLoader",
        module: "hawktui::widget::cancellable_loader",
        kind: ApiKind::Widget,
        summary: "A cancellable animated loader widget.",
        variants: &[],
        functions: &[
            ApiFn { name: "new", signature: "pub fn new(message: impl Into<String>) -> Self", role: "constructor", summary: "" },
            ApiFn { name: "cancel_hint", signature: "pub fn cancel_hint(mut self, hint: impl Into<String>) -> Self", role: "builder", summary: "" },
            ApiFn { name: "spinner_style", signature: "pub fn spinner_style(mut self, style: SpinnerStyle) -> Self", role: "builder", summary: "" },
            ApiFn { name: "style", signature: "pub fn style(mut self, style: Style) -> Self", role: "builder", summary: "" },
            ApiFn { name: "spinner_fg", signature: "pub fn spinner_fg(mut self, style: Style) -> Self", role: "builder", summary: "" },
            ApiFn { name: "hint_style", signature: "pub fn hint_style(mut self, style: Style) -> Self", role: "builder", summary: "" },
            ApiFn { name: "tick", signature: "pub fn tick(mut self, tick: usize) -> Self", role: "builder", summary: "" },
            ApiFn { name: "cancelled", signature: "pub fn cancelled(mut self, cancelled: bool) -> Self", role: "builder", summary: "" },
            ApiFn { name: "is_cancelled", signature: "pub fn is_cancelled(&self) -> bool", role: "method", summary: "" },
        ],
    },
    ApiType {
        name: "Canvas",
        module: "hawktui::widget::canvas",
        kind: ApiKind::Widget,
        summary: "A freeform drawing canvas using braille characters for sub-cell resolution.",
        variants: &[],
        functions: &[
            ApiFn { name: "new", signature: "pub fn new() -> Self", role: "constructor", summary: "" },
            ApiFn { name: "block", signature: "pub fn block(mut self, block: Block) -> Self", role: "builder", summary: "" },
            ApiFn { name: "x_bounds", signature: "pub fn x_bounds(mut self, bounds: [f64; 2]) -> Self", role: "builder", summary: "" },
            ApiFn { name: "y_bounds", signature: "pub fn y_bounds(mut self, bounds: [f64; 2]) -> Self", role: "builder", summary: "" },
            ApiFn { name: "style", signature: "pub fn style(mut self, style: Style) -> Self", role: "builder", summary: "" },
            ApiFn { name: "line", signature: "pub fn line(mut self, line: CanvasLine) -> Self", role: "builder", summary: "" },
            ApiFn { name: "rect", signature: "pub fn rect(mut self, rect: CanvasRect) -> Self", role: "builder", summary: "" },
            ApiFn { name: "circle", signature: "pub fn circle(mut self, circle: CanvasCircle) -> Self", role: "builder", summary: "Draw a circle outline." },
            ApiFn { name: "filled_rect", signature: "pub fn filled_rect(mut self, rect: CanvasFilledRect) -> Self", role: "builder", summary: "Draw a filled rectangle." },
            ApiFn { name: "shape", signature: "pub fn shape(mut self, shape: impl Shape + 'static) -> Self", role: "builder", summary: "Draw any custom [`Shape`]." },
            ApiFn { name: "map", signature: "pub fn map(mut self, map: CanvasMap) -> Self", role: "builder", summary: "Draw geographic paths." },
            ApiFn { name: "geographic", signature: "pub fn geographic(mut self) -> Self", role: "builder", summary: "Set whole-world bounds: longitude -180..180, latitude -90..90." },
            ApiFn { name: "points", signature: "pub fn points(mut self, points: Points) -> Self", role: "builder", summary: "" },
        ],
    },
    ApiType {
        name: "CanvasMap",
        module: "hawktui::widget::canvas",
        kind: ApiKind::Struct,
        summary: "Coastlines, borders, or any other geographic paths drawn on a canvas.",
        variants: &[],
        functions: &[
            ApiFn { name: "new", signature: "pub fn new(data: MapData) -> Self", role: "constructor", summary: "Draw `data` in the default color, connecting vertices." },
            ApiFn { name: "color", signature: "pub fn color(mut self, color: Color) -> Self", role: "builder", summary: "" },
            ApiFn { name: "resolution", signature: "pub fn resolution(mut self, resolution: MapResolution) -> Self", role: "builder", summary: "" },
            ApiFn { name: "connect", signature: "pub fn connect(mut self, connect: bool) -> Self", role: "builder", summary: "" },
        ],
    },
    ApiType {
        name: "Cell",
        module: "hawktui::core",
        kind: ApiKind::Struct,
        summary: "A single cell in the terminal buffer.",
        variants: &[],
        functions: &[
            ApiFn { name: "set_symbol", signature: "pub fn set_symbol(&mut self, symbol: &str) -> &mut Self", role: "method", summary: "Set the grapheme cluster for this cell." },
            ApiFn { name: "set_char", signature: "pub fn set_char(&mut self, ch: char) -> &mut Self", role: "method", summary: "Set a single character." },
            ApiFn { name: "symbol", signature: "pub fn symbol(&self) -> &str", role: "method", summary: "The grapheme cluster as a string slice." },
            ApiFn { name: "set_style", signature: "pub fn set_style(&mut self, style: Style) -> &mut Self", role: "method", summary: "Apply a style to this cell (merging)." },
            ApiFn { name: "style", signature: "pub fn style(&self) -> Style", role: "method", summary: "Get the current style of this cell." },
            ApiFn { name: "reset", signature: "pub fn reset(&mut self)", role: "method", summary: "Reset this cell to empty." },
            ApiFn { name: "is_empty", signature: "pub fn is_empty(&self) -> bool", role: "method", summary: "Whether this cell has the default empty content." },
        ],
    },
    ApiType {
        name: "Chart",
        module: "hawktui::widget::chart",
        kind: ApiKind::Widget,
        summary: "XY chart widget for line and scatter plots.",
        variants: &[],
        functions: &[
            ApiFn { name: "new", signature: "pub fn new(datasets: impl Into<Vec<Dataset>>) -> Self", role: "constructor", summary: "" },
            ApiFn { name: "block", signature: "pub fn block(mut self, block: Block) -> Self", role: "builder", summary: "" },
            ApiFn { name: "x_axis", signature: "pub fn x_axis(mut self, axis: Axis) -> Self", role: "builder", summary: "" },
            ApiFn { name: "y_axis", signature: "pub fn y_axis(mut self, axis: Axis) -> Self", role: "builder", summary: "" },
            ApiFn { name: "style", signature: "pub fn style(mut self, style: Style) -> Self", role: "builder", summary: "" },
            ApiFn { name: "legend_position", signature: "pub fn legend_position(mut self, pos: LegendPosition) -> Self", role: "builder", summary: "" },
        ],
    },
    ApiType {
        name: "Color",
        module: "hawktui::core",
        kind: ApiKind::Enum,
        summary: "Terminal color.",
        variants: &["Reset", "Black", "Red", "Green", "Yellow", "Blue", "Magenta", "Cyan", "Gray", "DarkGray", "LightRed", "LightGreen", "LightYellow", "LightBlue", "LightMagenta", "LightCyan", "White", "Indexed", "Rgb"],
        functions: &[
        ],
    },
    ApiType {
        name: "Command",
        module: "hawktui::runtime",
        kind: ApiKind::Enum,
        summary: "A command returned from [`Model::update`] to request side effects.",
        variants: &["None", "Quit", "Batch", "Message", "SetTickRate", "ExportOntology", "AgentAction", "Task"],
        functions: &[
        ],
    },
    ApiType {
        name: "Constraint",
        module: "hawktui::layout",
        kind: ApiKind::Enum,
        summary: "Size constraint for layout segments.",
        variants: &["Length", "Percentage", "Min", "Max", "Ratio", "Fill"],
        functions: &[
        ],
    },
    ApiType {
        name: "Dataset",
        module: "hawktui::widget::chart",
        kind: ApiKind::Struct,
        summary: "A series of data points with styling.",
        variants: &[],
        functions: &[
            ApiFn { name: "new", signature: "pub fn new(data: impl Into<Vec<DataPoint>>) -> Self", role: "constructor", summary: "" },
            ApiFn { name: "name", signature: "pub fn name(mut self, name: impl Into<Span>) -> Self", role: "builder", summary: "" },
            ApiFn { name: "marker", signature: "pub fn marker(mut self, marker: Marker) -> Self", role: "builder", summary: "" },
            ApiFn { name: "style", signature: "pub fn style(mut self, style: Style) -> Self", role: "builder", summary: "" },
            ApiFn { name: "graph_type", signature: "pub fn graph_type(mut self, graph_type: GraphType) -> Self", role: "builder", summary: "" },
        ],
    },
    ApiType {
        name: "Direction",
        module: "hawktui::layout",
        kind: ApiKind::Enum,
        summary: "Layouting direction.",
        variants: &["Vertical", "Horizontal"],
        functions: &[
        ],
    },
    ApiType {
        name: "Editor",
        module: "hawktui::widget::editor",
        kind: ApiKind::StatefulWidget { state: "EditorState" },
        summary: "A multi-line text editor widget.",
        variants: &[],
        functions: &[
            ApiFn { name: "new", signature: "pub fn new() -> Self", role: "constructor", summary: "" },
            ApiFn { name: "syntax", signature: "pub fn syntax(mut self, language: &'static Language) -> Self", role: "builder", summary: "Syntax-highlight the buffer as `language`." },
            ApiFn { name: "syntax_named", signature: "pub fn syntax_named(mut self, name: &str) -> Self", role: "builder", summary: "Syntax-highlight by language name, alias, or file extension." },
            ApiFn { name: "highlight_theme", signature: "pub fn highlight_theme(mut self, theme: HighlightTheme) -> Self", role: "builder", summary: "Palette for syntax highlighting." },
            ApiFn { name: "block", signature: "pub fn block(mut self, block: Block) -> Self", role: "builder", summary: "" },
            ApiFn { name: "style", signature: "pub fn style(mut self, style: Style) -> Self", role: "builder", summary: "" },
            ApiFn { name: "cursor_style", signature: "pub fn cursor_style(mut self, style: Style) -> Self", role: "builder", summary: "" },
            ApiFn { name: "show_line_numbers", signature: "pub fn show_line_numbers(mut self, show: bool) -> Self", role: "builder", summary: "" },
        ],
    },
    ApiType {
        name: "EditorState",
        module: "hawktui::widget::editor",
        kind: ApiKind::Struct,
        summary: "State for an [`Editor`] widget.",
        variants: &[],
        functions: &[
            ApiFn { name: "new", signature: "pub fn new() -> Self", role: "constructor", summary: "" },
            ApiFn { name: "with_text", signature: "pub fn with_text(text: &str) -> Self", role: "constructor", summary: "" },
            ApiFn { name: "text", signature: "pub fn text(&self) -> String", role: "method", summary: "Get the full text content." },
            ApiFn { name: "insert_char", signature: "pub fn insert_char(&mut self, ch: char)", role: "method", summary: "Insert a character at the cursor position." },
            ApiFn { name: "insert_newline", signature: "pub fn insert_newline(&mut self)", role: "method", summary: "Insert a newline, splitting the current line." },
            ApiFn { name: "delete_before", signature: "pub fn delete_before(&mut self)", role: "method", summary: "Delete the character before the cursor (backspace)." },
            ApiFn { name: "delete_after", signature: "pub fn delete_after(&mut self)", role: "method", summary: "Delete the character at the cursor (delete key)." },
            ApiFn { name: "move_left", signature: "pub fn move_left(&mut self)", role: "method", summary: "Move cursor left." },
            ApiFn { name: "move_right", signature: "pub fn move_right(&mut self)", role: "method", summary: "Move cursor right." },
            ApiFn { name: "move_up", signature: "pub fn move_up(&mut self)", role: "method", summary: "Move cursor up." },
            ApiFn { name: "move_down", signature: "pub fn move_down(&mut self)", role: "method", summary: "Move cursor down." },
            ApiFn { name: "move_home", signature: "pub fn move_home(&mut self)", role: "method", summary: "Move cursor to start of line." },
            ApiFn { name: "move_end", signature: "pub fn move_end(&mut self)", role: "method", summary: "Move cursor to end of line." },
        ],
    },
    ApiType {
        name: "Event",
        module: "hawktui::event",
        kind: ApiKind::Enum,
        summary: "A terminal event.",
        variants: &["Key", "Mouse", "Resize", "FocusGained", "FocusLost", "Paste", "Tick"],
        functions: &[
        ],
    },
    ApiType {
        name: "Flex",
        module: "hawktui::layout",
        kind: ApiKind::Enum,
        summary: "How to distribute excess space after constraints are satisfied.",
        variants: &["Start", "Center", "End", "SpaceBetween", "SpaceAround", "SpaceEvenly"],
        functions: &[
        ],
    },
    ApiType {
        name: "FocusManager",
        module: "hawktui::focus",
        kind: ApiKind::Struct,
        summary: "Manages keyboard focus across a set of focusable widgets.",
        variants: &[],
        functions: &[
            ApiFn { name: "new", signature: "pub fn new() -> Self", role: "constructor", summary: "Create a new empty focus manager." },
            ApiFn { name: "clear", signature: "pub fn clear(&mut self)", role: "method", summary: "Clear all registered widgets (call before each frame rebuild)." },
            ApiFn { name: "register", signature: "pub fn register(&mut self, agent_id: impl Into<String>)", role: "method", summary: "Register a focusable widget. Order of registration determines tab order." },
            ApiFn { name: "focused_id", signature: "pub fn focused_id(&self) -> Option<&str>", role: "method", summary: "The agent_id of the currently focused widget, if any." },
            ApiFn { name: "is_focused", signature: "pub fn is_focused(&self, agent_id: &str) -> bool", role: "method", summary: "Whether the given widget ID is currently focused." },
            ApiFn { name: "focus_next", signature: "pub fn focus_next(&mut self)", role: "method", summary: "Move focus to the next widget in the ring (Tab)." },
            ApiFn { name: "focus_previous", signature: "pub fn focus_previous(&mut self)", role: "method", summary: "Move focus to the previous widget in the ring (Shift+Tab)." },
            ApiFn { name: "focus_id", signature: "pub fn focus_id(&mut self, agent_id: &str) -> bool", role: "method", summary: "Focus a specific widget by agent_id. Returns true if found." },
            ApiFn { name: "blur", signature: "pub fn blur(&mut self)", role: "method", summary: "Remove focus entirely." },
            ApiFn { name: "len", signature: "pub fn len(&self) -> usize", role: "method", summary: "Number of registered focusable widgets." },
            ApiFn { name: "is_empty", signature: "pub fn is_empty(&self) -> bool", role: "method", summary: "Whether the focus ring is empty." },
            ApiFn { name: "ids", signature: "pub fn ids(&self) -> &[String]", role: "method", summary: "Get all registered widget IDs in tab order." },
        ],
    },
    ApiType {
        name: "Frame",
        module: "hawktui::terminal",
        kind: ApiKind::Struct,
        summary: "A single frame for rendering.",
        variants: &[],
        functions: &[
            ApiFn { name: "area", signature: "pub fn area(&self) -> Rect", role: "method", summary: "The full area available for rendering." },
            ApiFn { name: "buffer_mut", signature: "pub fn buffer_mut(&mut self) -> &mut Buffer", role: "method", summary: "The underlying buffer." },
            ApiFn { name: "render_widget", signature: "pub fn render_widget(&mut self, widget: impl Widget, area: Rect)", role: "method", summary: "Render a widget into the given area." },
            ApiFn { name: "render_stateful_widget", signature: "pub fn render_stateful_widget<W: StatefulWidget>( &mut self, widget: W, area: Rect, state: &mut W::State, )", role: "method", summary: "Render a stateful widget into the given area." },
            ApiFn { name: "set_cursor_position", signature: "pub fn set_cursor_position(&mut self, position: Position)", role: "method", summary: "Set the cursor position (makes it visible for this frame)." },
            ApiFn { name: "register_clickable", signature: "pub fn register_clickable(&mut self, agent_id: impl Into<String>, area: Rect, z_index: u16)", role: "method", summary: "Register a clickable region for mouse hit-testing." },
        ],
    },
    ApiType {
        name: "Gauge",
        module: "hawktui::widget::gauge",
        kind: ApiKind::Widget,
        summary: "A progress bar widget.",
        variants: &[],
        functions: &[
            ApiFn { name: "new", signature: "pub fn new() -> Self", role: "constructor", summary: "" },
            ApiFn { name: "block", signature: "pub fn block(mut self, block: Block) -> Self", role: "builder", summary: "" },
            ApiFn { name: "ratio", signature: "pub fn ratio(mut self, ratio: f64) -> Self", role: "builder", summary: "Set the ratio (0.0..=1.0). Values are clamped." },
            ApiFn { name: "percent", signature: "pub fn percent(mut self, percent: u16) -> Self", role: "builder", summary: "Set from a percentage (0..=100)." },
            ApiFn { name: "label", signature: "pub fn label(mut self, label: impl Into<Span>) -> Self", role: "builder", summary: "" },
            ApiFn { name: "style", signature: "pub fn style(mut self, style: Style) -> Self", role: "builder", summary: "" },
            ApiFn { name: "gauge_style", signature: "pub fn gauge_style(mut self, style: Style) -> Self", role: "builder", summary: "" },
        ],
    },
    ApiType {
        name: "GraphType",
        module: "hawktui::widget::chart",
        kind: ApiKind::Enum,
        summary: "How to connect data points.",
        variants: &["Line", "Scatter"],
        functions: &[
        ],
    },
    ApiType {
        name: "HitMap",
        module: "hawktui::event",
        kind: ApiKind::Struct,
        summary: "Manages hit-testing for clickable regions.",
        variants: &[],
        functions: &[
            ApiFn { name: "new", signature: "pub fn new() -> Self", role: "constructor", summary: "Create an empty hit map." },
            ApiFn { name: "clear", signature: "pub fn clear(&mut self)", role: "method", summary: "Clear all registered regions (called before each frame)." },
            ApiFn { name: "register", signature: "pub fn register( &mut self, agent_id: impl Into<String>, area: crate::core::rect::Rect, z_index: u16, )", role: "method", summary: "Register a clickable region." },
            ApiFn { name: "hit_test", signature: "pub fn hit_test(&self, x: u16, y: u16) -> Option<HitTestResult>", role: "method", summary: "Resolve a position to the topmost widget that contains it." },
        ],
    },
    ApiType {
        name: "Image",
        module: "hawktui::widget::image",
        kind: ApiKind::Widget,
        summary: "An image widget that renders inline images in supported terminals.",
        variants: &[],
        functions: &[
            ApiFn { name: "new", signature: "pub fn new(data: Vec<u8>, mime_type: impl Into<String>) -> Self", role: "constructor", summary: "Create a new image widget from raw bytes and MIME type." },
            ApiFn { name: "from_rgba", signature: "pub fn from_rgba(width: u32, height: u32, rgba: Vec<u8>) -> Option<Self>", role: "constructor", summary: "Build an image from decoded RGBA8 pixels, rendered with half-blocks." },
            ApiFn { name: "pixels", signature: "pub fn pixels(mut self, pixels: Pixels) -> Self", role: "builder", summary: "Attach decoded pixels to an image built from encoded bytes, so it can" },
            ApiFn { name: "protocol", signature: "pub fn protocol(mut self, protocol: ImageProtocol) -> Self", role: "builder", summary: "Set the rendering protocol." },
            ApiFn { name: "block", signature: "pub fn block(mut self, block: Block) -> Self", role: "builder", summary: "" },
            ApiFn { name: "style", signature: "pub fn style(mut self, style: Style) -> Self", role: "builder", summary: "" },
            ApiFn { name: "fallback_text", signature: "pub fn fallback_text(mut self, text: impl Into<String>) -> Self", role: "builder", summary: "Set fallback text for unsupported terminals." },
            ApiFn { name: "max_width", signature: "pub fn max_width(mut self, w: u16) -> Self", role: "builder", summary: "" },
            ApiFn { name: "max_height", signature: "pub fn max_height(mut self, h: u16) -> Self", role: "builder", summary: "" },
            ApiFn { name: "detect_protocol", signature: "pub fn detect_protocol() -> ImageProtocol", role: "constructor", summary: "Detect the best protocol based on environment variables." },
        ],
    },
    ApiType {
        name: "ImageProtocol",
        module: "hawktui::widget::image",
        kind: ApiKind::Enum,
        summary: "Image rendering protocol.",
        variants: &["Kitty", "ITerm2", "Sixel", "HalfBlock", "Fallback"],
        functions: &[
        ],
    },
    ApiType {
        name: "Input",
        module: "hawktui::widget::input",
        kind: ApiKind::Struct,
        summary: "A single-line text input widget.",
        variants: &[],
        functions: &[
            ApiFn { name: "new", signature: "pub fn new() -> Self", role: "constructor", summary: "" },
            ApiFn { name: "block", signature: "pub fn block(mut self, block: Block) -> Self", role: "builder", summary: "" },
            ApiFn { name: "style", signature: "pub fn style(mut self, style: Style) -> Self", role: "builder", summary: "" },
            ApiFn { name: "cursor_style", signature: "pub fn cursor_style(mut self, style: Style) -> Self", role: "builder", summary: "" },
            ApiFn { name: "placeholder", signature: "pub fn placeholder(mut self, placeholder: impl Into<String>) -> Self", role: "builder", summary: "" },
            ApiFn { name: "placeholder_style", signature: "pub fn placeholder_style(mut self, style: Style) -> Self", role: "builder", summary: "" },
        ],
    },
    ApiType {
        name: "InputState",
        module: "hawktui::widget::input",
        kind: ApiKind::Struct,
        summary: "State for an [`Input`] widget.",
        variants: &[],
        functions: &[
            ApiFn { name: "new", signature: "pub fn new() -> Self", role: "constructor", summary: "" },
            ApiFn { name: "with_value", signature: "pub fn with_value(mut self, value: impl Into<String>) -> Self", role: "builder", summary: "" },
            ApiFn { name: "insert_char", signature: "pub fn insert_char(&mut self, ch: char)", role: "method", summary: "" },
            ApiFn { name: "delete_char_before", signature: "pub fn delete_char_before(&mut self)", role: "method", summary: "" },
            ApiFn { name: "delete_char_after", signature: "pub fn delete_char_after(&mut self)", role: "method", summary: "" },
            ApiFn { name: "move_left", signature: "pub fn move_left(&mut self)", role: "method", summary: "" },
            ApiFn { name: "move_right", signature: "pub fn move_right(&mut self)", role: "method", summary: "" },
            ApiFn { name: "move_start", signature: "pub fn move_start(&mut self)", role: "method", summary: "" },
            ApiFn { name: "move_end", signature: "pub fn move_end(&mut self)", role: "method", summary: "" },
            ApiFn { name: "clear", signature: "pub fn clear(&mut self)", role: "method", summary: "" },
        ],
    },
    ApiType {
        name: "KeyCode",
        module: "hawktui::event",
        kind: ApiKind::Enum,
        summary: "Key code.",
        variants: &["Char", "F", "Backspace", "Enter", "Tab", "BackTab", "Esc", "Left", "Right", "Up", "Down", "Home", "End", "PageUp", "PageDown", "Insert", "Delete", "Null"],
        functions: &[
        ],
    },
    ApiType {
        name: "KeyEvent",
        module: "hawktui::event",
        kind: ApiKind::Struct,
        summary: "A keyboard event.",
        variants: &[],
        functions: &[
            ApiFn { name: "new", signature: "pub fn new(code: KeyCode, modifiers: KeyModifiers) -> Self", role: "constructor", summary: "Create a new key-press event with the given code and modifiers." },
            ApiFn { name: "is_ctrl", signature: "pub fn is_ctrl(&self, code: KeyCode) -> bool", role: "method", summary: "Convenience: is this a Ctrl+\\<key\\> press?" },
            ApiFn { name: "is_key", signature: "pub fn is_key(&self, code: KeyCode) -> bool", role: "method", summary: "Convenience: matches a key code with no modifiers." },
        ],
    },
    ApiType {
        name: "KeyEventKind",
        module: "hawktui::event",
        kind: ApiKind::Enum,
        summary: "The kind of key event.",
        variants: &["Press", "Release", "Repeat"],
        functions: &[
        ],
    },
    ApiType {
        name: "Layout",
        module: "hawktui::layout",
        kind: ApiKind::Struct,
        summary: "Layout builder.",
        variants: &[],
        functions: &[
            ApiFn { name: "new", signature: "pub fn new(direction: Direction, constraints: impl IntoIterator<Item = Constraint>) -> Self", role: "constructor", summary: "" },
            ApiFn { name: "vertical", signature: "pub fn vertical(constraints: impl IntoIterator<Item = Constraint>) -> Self", role: "constructor", summary: "" },
            ApiFn { name: "horizontal", signature: "pub fn horizontal(constraints: impl IntoIterator<Item = Constraint>) -> Self", role: "constructor", summary: "" },
            ApiFn { name: "direction", signature: "pub fn direction(mut self, direction: Direction) -> Self", role: "builder", summary: "" },
            ApiFn { name: "constraints", signature: "pub fn constraints(mut self, constraints: impl IntoIterator<Item = Constraint>) -> Self", role: "builder", summary: "" },
            ApiFn { name: "margin", signature: "pub fn margin(mut self, margin: Margin) -> Self", role: "builder", summary: "" },
            ApiFn { name: "flex", signature: "pub fn flex(mut self, flex: Flex) -> Self", role: "builder", summary: "" },
            ApiFn { name: "spacing", signature: "pub fn spacing(mut self, spacing: i16) -> Self", role: "builder", summary: "" },
            ApiFn { name: "gap", signature: "pub fn gap(mut self, gap: u16) -> Self", role: "builder", summary: "Fixed space between adjacent segments — the flexbox `gap`." },
            ApiFn { name: "padding", signature: "pub fn padding(mut self, padding: u16) -> Self", role: "builder", summary: "Inset the area on all four sides before splitting — the CSS `padding`." },
            ApiFn { name: "horizontal_margin", signature: "pub fn horizontal_margin(mut self, margin: u16) -> Self", role: "builder", summary: "Inset the left and right edges before splitting." },
            ApiFn { name: "vertical_margin", signature: "pub fn vertical_margin(mut self, margin: u16) -> Self", role: "builder", summary: "Inset the top and bottom edges before splitting." },
            ApiFn { name: "split", signature: "pub fn split(&self, area: Rect) -> Rc<[Rect]>", role: "method", summary: "Split the given area into segments according to constraints." },
            ApiFn { name: "areas", signature: "pub fn areas<const N: usize>(&self, area: Rect) -> [Rect; N]", role: "method", summary: "Split into a fixed number of areas, destructurable at the call site." },
            ApiFn { name: "solve", signature: "pub fn solve(&self, area: Rect) -> Vec<Rect>", role: "method", summary: "Solve the layout from scratch, bypassing the memo cache." },
        ],
    },
    ApiType {
        name: "LegendPosition",
        module: "hawktui::widget::chart",
        kind: ApiKind::Enum,
        summary: "Position for the chart legend.",
        variants: &["TopLeft", "TopRight", "BottomLeft", "BottomRight"],
        functions: &[
        ],
    },
    ApiType {
        name: "Line",
        module: "hawktui::core",
        kind: ApiKind::Struct,
        summary: "A single line of styled text, composed of multiple [`Span`]s.",
        variants: &[],
        functions: &[
            ApiFn { name: "raw", signature: "pub fn raw(content: impl Into<Cow<'static, str>>) -> Self", role: "constructor", summary: "" },
            ApiFn { name: "styled", signature: "pub fn styled(content: impl Into<Cow<'static, str>>, style: Style) -> Self", role: "constructor", summary: "" },
            ApiFn { name: "alignment", signature: "pub fn alignment(mut self, alignment: Alignment) -> Self", role: "builder", summary: "" },
            ApiFn { name: "left", signature: "pub fn left(self) -> Self", role: "builder", summary: "" },
            ApiFn { name: "centered", signature: "pub fn centered(self) -> Self", role: "builder", summary: "" },
            ApiFn { name: "right", signature: "pub fn right(self) -> Self", role: "builder", summary: "" },
            ApiFn { name: "width", signature: "pub fn width(&self) -> usize", role: "method", summary: "Total visible width of this line." },
        ],
    },
    ApiType {
        name: "LineGauge",
        module: "hawktui::widget::line_gauge",
        kind: ApiKind::Widget,
        summary: "A thin, single-line progress gauge.",
        variants: &[],
        functions: &[
            ApiFn { name: "new", signature: "pub fn new() -> Self", role: "constructor", summary: "" },
            ApiFn { name: "block", signature: "pub fn block(mut self, block: Block) -> Self", role: "builder", summary: "" },
            ApiFn { name: "ratio", signature: "pub fn ratio(mut self, ratio: f64) -> Self", role: "builder", summary: "Set the ratio (0.0..=1.0). Clamped to valid range." },
            ApiFn { name: "percent", signature: "pub fn percent(mut self, percent: u16) -> Self", role: "builder", summary: "Set from a percentage (0..=100)." },
            ApiFn { name: "label", signature: "pub fn label(mut self, label: impl Into<Span>) -> Self", role: "builder", summary: "" },
            ApiFn { name: "style", signature: "pub fn style(mut self, style: Style) -> Self", role: "builder", summary: "" },
            ApiFn { name: "line_style", signature: "pub fn line_style(mut self, style: Style) -> Self", role: "builder", summary: "" },
            ApiFn { name: "filled_symbol", signature: "pub fn filled_symbol(mut self, symbol: &'static str) -> Self", role: "builder", summary: "" },
            ApiFn { name: "unfilled_symbol", signature: "pub fn unfilled_symbol(mut self, symbol: &'static str) -> Self", role: "builder", summary: "" },
        ],
    },
    ApiType {
        name: "List",
        module: "hawktui::widget::list",
        kind: ApiKind::StatefulWidget { state: "ListState" },
        summary: "A scrollable list widget with selection support.",
        variants: &[],
        functions: &[
            ApiFn { name: "new", signature: "pub fn new(items: impl IntoIterator<Item = impl Into<ListItem>>) -> Self", role: "constructor", summary: "" },
            ApiFn { name: "block", signature: "pub fn block(mut self, block: Block) -> Self", role: "builder", summary: "" },
            ApiFn { name: "style", signature: "pub fn style(mut self, style: Style) -> Self", role: "builder", summary: "" },
            ApiFn { name: "highlight_style", signature: "pub fn highlight_style(mut self, style: Style) -> Self", role: "builder", summary: "" },
            ApiFn { name: "highlight_symbol", signature: "pub fn highlight_symbol(mut self, symbol: impl Into<String>) -> Self", role: "builder", summary: "" },
            ApiFn { name: "scroll_padding", signature: "pub fn scroll_padding(mut self, padding: usize) -> Self", role: "builder", summary: "Keep `padding` rows visible above and below the selection when" },
            ApiFn { name: "direction", signature: "pub fn direction(mut self, direction: ListDirection) -> Self", role: "builder", summary: "" },
            ApiFn { name: "len", signature: "pub fn len(&self) -> usize", role: "method", summary: "" },
            ApiFn { name: "is_empty", signature: "pub fn is_empty(&self) -> bool", role: "method", summary: "" },
        ],
    },
    ApiType {
        name: "ListDirection",
        module: "hawktui::widget::list",
        kind: ApiKind::Enum,
        summary: "Direction in which list items are rendered.",
        variants: &["TopToBottom", "BottomToTop"],
        functions: &[
        ],
    },
    ApiType {
        name: "ListItem",
        module: "hawktui::widget::list",
        kind: ApiKind::Struct,
        summary: "A single item in a [`List`].",
        variants: &[],
        functions: &[
            ApiFn { name: "new", signature: "pub fn new(content: impl Into<Line>) -> Self", role: "constructor", summary: "" },
            ApiFn { name: "style", signature: "pub fn style(mut self, style: Style) -> Self", role: "builder", summary: "" },
        ],
    },
    ApiType {
        name: "ListState",
        module: "hawktui::widget::list",
        kind: ApiKind::Struct,
        summary: "State for a [`List`] widget.",
        variants: &[],
        functions: &[
            ApiFn { name: "new", signature: "pub fn new() -> Self", role: "constructor", summary: "" },
            ApiFn { name: "with_selected", signature: "pub fn with_selected(mut self, selected: Option<usize>) -> Self", role: "builder", summary: "" },
            ApiFn { name: "select", signature: "pub fn select(&mut self, index: Option<usize>)", role: "method", summary: "" },
            ApiFn { name: "select_next", signature: "pub fn select_next(&mut self, item_count: usize)", role: "method", summary: "" },
            ApiFn { name: "select_previous", signature: "pub fn select_previous(&mut self)", role: "method", summary: "" },
            ApiFn { name: "select_first", signature: "pub fn select_first(&mut self)", role: "method", summary: "" },
            ApiFn { name: "select_last", signature: "pub fn select_last(&mut self, item_count: usize)", role: "method", summary: "" },
        ],
    },
    ApiType {
        name: "Loader",
        module: "hawktui::widget::loader",
        kind: ApiKind::Widget,
        summary: "An animated spinner/loader widget.",
        variants: &[],
        functions: &[
            ApiFn { name: "new", signature: "pub fn new(message: impl Into<String>) -> Self", role: "constructor", summary: "" },
            ApiFn { name: "spinner_style", signature: "pub fn spinner_style(mut self, style: SpinnerStyle) -> Self", role: "builder", summary: "" },
            ApiFn { name: "style", signature: "pub fn style(mut self, style: Style) -> Self", role: "builder", summary: "" },
            ApiFn { name: "spinner_fg", signature: "pub fn spinner_fg(mut self, style: Style) -> Self", role: "builder", summary: "" },
            ApiFn { name: "tick", signature: "pub fn tick(mut self, tick: usize) -> Self", role: "builder", summary: "" },
        ],
    },
    ApiType {
        name: "MapData",
        module: "hawktui::widget::canvas",
        kind: ApiKind::Struct,
        summary: "Geographic paths in `(longitude, latitude)` degrees.",
        variants: &[],
        functions: &[
            ApiFn { name: "new", signature: "pub fn new() -> Self", role: "constructor", summary: "An empty dataset." },
            ApiFn { name: "path", signature: "pub fn path(mut self, points: impl IntoIterator<Item = (f64, f64)>) -> Self", role: "builder", summary: "Add one polyline." },
            ApiFn { name: "from_paths", signature: "pub fn from_paths(paths: impl IntoIterator<Item = Vec<(f64, f64)>>) -> Self", role: "constructor", summary: "Build from many polylines at once." },
            ApiFn { name: "from_geojson", signature: "pub fn from_geojson(source: &str) -> Option<Self>", role: "constructor", summary: "Read every line and polygon ring out of a GeoJSON document." },
            ApiFn { name: "paths", signature: "pub fn paths(&self) -> &[Vec<(f64, f64)>]", role: "method", summary: "The polylines, in insertion order." },
            ApiFn { name: "point_count", signature: "pub fn point_count(&self) -> usize", role: "method", summary: "Total number of vertices across all paths." },
            ApiFn { name: "is_empty", signature: "pub fn is_empty(&self) -> bool", role: "method", summary: "True when there is nothing to draw." },
        ],
    },
    ApiType {
        name: "MapResolution",
        module: "hawktui::widget::canvas",
        kind: ApiKind::Enum,
        summary: "How densely a [`CanvasMap`] samples its data.",
        variants: &["Low", "High"],
        functions: &[
        ],
    },
    ApiType {
        name: "Markdown",
        module: "hawktui::widget::markdown",
        kind: ApiKind::Widget,
        summary: "A widget that renders Markdown text with basic formatting.",
        variants: &[],
        functions: &[
            ApiFn { name: "new", signature: "pub fn new(source: impl Into<String>) -> Self", role: "constructor", summary: "" },
            ApiFn { name: "highlight", signature: "pub fn highlight(mut self, highlight: bool) -> Self", role: "builder", summary: "Syntax-highlight fenced code blocks whose fence names a known language." },
            ApiFn { name: "highlight_theme", signature: "pub fn highlight_theme(mut self, theme: HighlightTheme) -> Self", role: "builder", summary: "Palette for highlighted code blocks." },
            ApiFn { name: "block", signature: "pub fn block(mut self, block: Block) -> Self", role: "builder", summary: "" },
            ApiFn { name: "style", signature: "pub fn style(mut self, style: Style) -> Self", role: "builder", summary: "" },
            ApiFn { name: "heading_style", signature: "pub fn heading_style(mut self, style: Style) -> Self", role: "builder", summary: "" },
            ApiFn { name: "code_style", signature: "pub fn code_style(mut self, style: Style) -> Self", role: "builder", summary: "" },
        ],
    },
    ApiType {
        name: "Marker",
        module: "hawktui::widget::chart",
        kind: ApiKind::Enum,
        summary: "Marker style for data points.",
        variants: &["Braille", "Block", "HalfBlock", "Char"],
        functions: &[
        ],
    },
    ApiType {
        name: "ModalBox",
        module: "hawktui::overlay",
        kind: ApiKind::Widget,
        summary: "A simple centered modal box widget.",
        variants: &[],
        functions: &[
            ApiFn { name: "new", signature: "pub fn new(title: impl Into<String>) -> Self", role: "constructor", summary: "Create a new modal box with the given title." },
            ApiFn { name: "style", signature: "pub fn style(mut self, style: Style) -> Self", role: "builder", summary: "Set the content background style." },
            ApiFn { name: "border_style", signature: "pub fn border_style(mut self, style: Style) -> Self", role: "builder", summary: "Set the border style." },
            ApiFn { name: "width_percent", signature: "pub fn width_percent(mut self, pct: u16) -> Self", role: "builder", summary: "Set width as a percentage of the parent area (0–100)." },
            ApiFn { name: "height_percent", signature: "pub fn height_percent(mut self, pct: u16) -> Self", role: "builder", summary: "Set height as a percentage of the parent area (0–100)." },
            ApiFn { name: "inner_area", signature: "pub fn inner_area(&self, parent: Rect) -> Rect", role: "method", summary: "Calculate the inner area for the modal content, given the parent area." },
        ],
    },
    ApiType {
        name: "Model",
        module: "hawktui::runtime",
        kind: ApiKind::Trait,
        summary: "The core trait for application models (Elm Architecture).",
        variants: &[],
        functions: &[
            ApiFn { name: "update", signature: "fn update(&mut self, msg: Self::Msg) -> Command<Self::Msg>", role: "required", summary: "" },
            ApiFn { name: "view", signature: "fn view(&self, frame: &mut crate::terminal::Frame<'_>)", role: "required", summary: "" },
            ApiFn { name: "handle_event", signature: "fn handle_event(&self, event: Event) -> Option<Self::Msg>", role: "required", summary: "" },
            ApiFn { name: "init", signature: "fn init(&self) -> Command<Self::Msg>", role: "provided", summary: "" },
            ApiFn { name: "register_ontology", signature: "fn register_ontology(&self, _registry: &mut OntologyRegistry)", role: "provided", summary: "" },
        ],
    },
    ApiType {
        name: "MouseButton",
        module: "hawktui::event",
        kind: ApiKind::Enum,
        summary: "Mouse button.",
        variants: &["Left", "Right", "Middle", "None"],
        functions: &[
        ],
    },
    ApiType {
        name: "MouseEvent",
        module: "hawktui::event",
        kind: ApiKind::Struct,
        summary: "A mouse event.",
        variants: &[],
        functions: &[
            ApiFn { name: "is_click", signature: "pub fn is_click(&self) -> bool", role: "method", summary: "Whether this is a click (button down) event." },
            ApiFn { name: "is_drag", signature: "pub fn is_drag(&self) -> bool", role: "method", summary: "Whether this is a drag event." },
            ApiFn { name: "is_scroll", signature: "pub fn is_scroll(&self) -> bool", role: "method", summary: "Whether this is a scroll event." },
            ApiFn { name: "clicked_in", signature: "pub fn clicked_in(&self, area: crate::core::rect::Rect) -> bool", role: "method", summary: "Whether the given rect was clicked." },
        ],
    },
    ApiType {
        name: "MouseEventKind",
        module: "hawktui::event",
        kind: ApiKind::Enum,
        summary: "The kind of mouse event.",
        variants: &["Down", "Up", "Drag", "Moved", "ScrollUp", "ScrollDown", "ScrollLeft", "ScrollRight"],
        functions: &[
        ],
    },
    ApiType {
        name: "OverlayStack",
        module: "hawktui::overlay",
        kind: ApiKind::Struct,
        summary: "Manages a stack of overlays rendered on top of the main content.",
        variants: &[],
        functions: &[
            ApiFn { name: "new", signature: "pub fn new() -> Self", role: "constructor", summary: "Create an empty overlay stack." },
            ApiFn { name: "push", signature: "pub fn push(&mut self, overlay: Overlay)", role: "method", summary: "Push an overlay onto the stack." },
            ApiFn { name: "remove", signature: "pub fn remove(&mut self, id: &str) -> bool", role: "method", summary: "Remove an overlay by ID. Returns true if found and removed." },
            ApiFn { name: "top", signature: "pub fn top(&self) -> Option<&Overlay>", role: "method", summary: "The topmost overlay, if any." },
            ApiFn { name: "has_focus_capture", signature: "pub fn has_focus_capture(&self) -> bool", role: "method", summary: "Whether any overlay is currently capturing focus." },
            ApiFn { name: "focus_capture_id", signature: "pub fn focus_capture_id(&self) -> Option<&str>", role: "method", summary: "The ID of the overlay currently capturing focus, if any." },
            ApiFn { name: "is_empty", signature: "pub fn is_empty(&self) -> bool", role: "method", summary: "Whether the stack is empty." },
            ApiFn { name: "len", signature: "pub fn len(&self) -> usize", role: "method", summary: "Number of overlays on the stack." },
            ApiFn { name: "iter", signature: "pub fn iter(&self) -> impl Iterator<Item = &Overlay>", role: "method", summary: "Iterate over overlays from bottom to top." },
            ApiFn { name: "clear", signature: "pub fn clear(&mut self)", role: "method", summary: "Clear all overlays." },
        ],
    },
    ApiType {
        name: "Painter",
        module: "hawktui::widget::canvas",
        kind: ApiKind::Struct,
        summary: "Painter provides coordinate mapping and drawing operations for shapes.",
        variants: &[],
        functions: &[
            ApiFn { name: "new", signature: "pub fn new(width: usize, height: usize, x_bounds: [f64; 2], y_bounds: [f64; 2]) -> Self", role: "constructor", summary: "" },
            ApiFn { name: "canvas_to_grid", signature: "pub fn canvas_to_grid(&self, x: f64, y: f64) -> (usize, usize)", role: "method", summary: "Convert canvas coordinates to braille grid coordinates." },
            ApiFn { name: "paint", signature: "pub fn paint(&mut self, x: usize, y: usize, color: Color)", role: "method", summary: "" },
            ApiFn { name: "into_grid", signature: "pub fn into_grid(self) -> BrailleGrid", role: "builder", summary: "" },
        ],
    },
    ApiType {
        name: "Paragraph",
        module: "hawktui::widget::paragraph",
        kind: ApiKind::Widget,
        summary: "A text display widget with optional wrapping, scrolling, and alignment.",
        variants: &[],
        functions: &[
            ApiFn { name: "new", signature: "pub fn new(text: impl Into<Text>) -> Self", role: "constructor", summary: "" },
            ApiFn { name: "block", signature: "pub fn block(mut self, block: Block) -> Self", role: "builder", summary: "" },
            ApiFn { name: "style", signature: "pub fn style(mut self, style: Style) -> Self", role: "builder", summary: "" },
            ApiFn { name: "wrap", signature: "pub fn wrap(mut self, wrap: Wrap) -> Self", role: "builder", summary: "" },
            ApiFn { name: "scroll", signature: "pub fn scroll(mut self, scroll: (u16, u16)) -> Self", role: "builder", summary: "" },
            ApiFn { name: "alignment", signature: "pub fn alignment(mut self, alignment: Alignment) -> Self", role: "builder", summary: "" },
            ApiFn { name: "left", signature: "pub fn left(self) -> Self", role: "builder", summary: "" },
            ApiFn { name: "centered", signature: "pub fn centered(self) -> Self", role: "builder", summary: "" },
            ApiFn { name: "right", signature: "pub fn right(self) -> Self", role: "builder", summary: "" },
        ],
    },
    ApiType {
        name: "Pixels",
        module: "hawktui::widget::image",
        kind: ApiKind::Struct,
        summary: "Decoded pixel data for half-block rendering.",
        variants: &[],
        functions: &[
            ApiFn { name: "from_rgba", signature: "pub fn from_rgba(width: u32, height: u32, rgba: Vec<u8>) -> Option<Self>", role: "constructor", summary: "Wrap RGBA8 samples. Returns `None` if the buffer length does not match" },
            ApiFn { name: "from_rgb", signature: "pub fn from_rgb(width: u32, height: u32, rgb: &[u8]) -> Option<Self>", role: "constructor", summary: "Wrap RGB8 samples, treating every pixel as fully opaque." },
            ApiFn { name: "width", signature: "pub fn width(&self) -> u32", role: "method", summary: "Image width in pixels." },
            ApiFn { name: "height", signature: "pub fn height(&self) -> u32", role: "method", summary: "Image height in pixels." },
            ApiFn { name: "to_sixel", signature: "pub fn to_sixel(&self) -> Option<String>", role: "method", summary: "Encode these pixels as a Sixel escape sequence." },
        ],
    },
    ApiType {
        name: "Program",
        module: "hawktui::runtime",
        kind: ApiKind::Struct,
        summary: "The main application runner.",
        variants: &[],
        functions: &[
            ApiFn { name: "new", signature: "pub fn new(model: M, backend: B) -> io::Result<Self>", role: "constructor", summary: "Create a new program with the given model and backend." },
            ApiFn { name: "with_options", signature: "pub fn with_options(mut self, options: ProgramOptions) -> Self", role: "builder", summary: "Override the default program options." },
            ApiFn { name: "model", signature: "pub fn model(&self) -> &M", role: "method", summary: "Access the current model state." },
            ApiFn { name: "ontology", signature: "pub fn ontology(&self) -> &OntologyRegistry", role: "method", summary: "Access the ontology registry." },
            ApiFn { name: "run", signature: "pub fn run(mut self) -> io::Result<M>", role: "builder", summary: "Run the application event loop. Returns the final model when the app quits." },
        ],
    },
    ApiType {
        name: "Rect",
        module: "hawktui::core",
        kind: ApiKind::Struct,
        summary: "A rectangular area in terminal coordinates.",
        variants: &[],
        functions: &[
            ApiFn { name: "intersection", signature: "pub fn intersection(&self, other: Rect) -> Rect", role: "method", summary: "Returns the intersection of two rectangles." },
            ApiFn { name: "union", signature: "pub fn union(&self, other: Rect) -> Rect", role: "method", summary: "Returns the smallest rectangle that contains both." },
            ApiFn { name: "contains", signature: "pub fn contains(&self, pos: Position) -> bool", role: "method", summary: "Whether this rectangle contains a position." },
            ApiFn { name: "inner", signature: "pub fn inner(&self, margin: Margin) -> Rect", role: "method", summary: "Create a new rect with uniform inner margin applied." },
            ApiFn { name: "positions", signature: "pub fn positions(&self) -> impl Iterator<Item = Position> + '_", role: "method", summary: "Iterator over all positions in this rectangle, row by row." },
            ApiFn { name: "rows", signature: "pub fn rows(&self) -> impl Iterator<Item = u16>", role: "method", summary: "Iterator over row indices." },
            ApiFn { name: "columns", signature: "pub fn columns(&self) -> impl Iterator<Item = u16>", role: "method", summary: "Iterator over column indices." },
        ],
    },
    ApiType {
        name: "Scrollbar",
        module: "hawktui::widget::scrollbar",
        kind: ApiKind::StatefulWidget { state: "ScrollbarState" },
        summary: "A scrollbar indicator widget.",
        variants: &[],
        functions: &[
            ApiFn { name: "new", signature: "pub fn new(orientation: ScrollbarOrientation) -> Self", role: "constructor", summary: "" },
            ApiFn { name: "style", signature: "pub fn style(mut self, style: Style) -> Self", role: "builder", summary: "" },
            ApiFn { name: "thumb_style", signature: "pub fn thumb_style(mut self, style: Style) -> Self", role: "builder", summary: "" },
            ApiFn { name: "symbols", signature: "pub fn symbols(mut self, symbols: ScrollbarSymbols) -> Self", role: "builder", summary: "" },
        ],
    },
    ApiType {
        name: "ScrollbarOrientation",
        module: "hawktui::widget::scrollbar",
        kind: ApiKind::Enum,
        summary: "Orientation of the scrollbar track.",
        variants: &["Vertical", "Horizontal"],
        functions: &[
        ],
    },
    ApiType {
        name: "ScrollbarState",
        module: "hawktui::widget::scrollbar",
        kind: ApiKind::Struct,
        summary: "Scrollbar state tracking content and viewport sizes.",
        variants: &[],
        functions: &[
            ApiFn { name: "new", signature: "pub fn new(content_length: usize, viewport_length: usize) -> Self", role: "constructor", summary: "" },
            ApiFn { name: "position", signature: "pub fn position(mut self, position: usize) -> Self", role: "builder", summary: "" },
            ApiFn { name: "scroll_down", signature: "pub fn scroll_down(&mut self, amount: usize)", role: "method", summary: "" },
            ApiFn { name: "scroll_up", signature: "pub fn scroll_up(&mut self, amount: usize)", role: "method", summary: "" },
            ApiFn { name: "scroll_to_top", signature: "pub fn scroll_to_top(&mut self)", role: "method", summary: "" },
            ApiFn { name: "scroll_to_bottom", signature: "pub fn scroll_to_bottom(&mut self)", role: "method", summary: "" },
            ApiFn { name: "fraction", signature: "pub fn fraction(&self) -> f64", role: "method", summary: "Returns the fraction scrolled (0.0..=1.0)." },
        ],
    },
    ApiType {
        name: "SelectItem",
        module: "hawktui::widget::select_list",
        kind: ApiKind::Struct,
        summary: "An item in a [`SelectList`].",
        variants: &[],
        functions: &[
            ApiFn { name: "new", signature: "pub fn new(label: impl Into<String>, value: impl Into<String>) -> Self", role: "constructor", summary: "" },
            ApiFn { name: "simple", signature: "pub fn simple(s: impl Into<String>) -> Self", role: "constructor", summary: "Convenience: label and value are the same." },
        ],
    },
    ApiType {
        name: "SelectList",
        module: "hawktui::widget::select_list",
        kind: ApiKind::StatefulWidget { state: "SelectListState" },
        summary: "An interactive select list widget.",
        variants: &[],
        functions: &[
            ApiFn { name: "new", signature: "pub fn new(items: Vec<SelectItem>) -> Self", role: "constructor", summary: "" },
            ApiFn { name: "block", signature: "pub fn block(mut self, block: Block) -> Self", role: "builder", summary: "" },
            ApiFn { name: "mode", signature: "pub fn mode(mut self, mode: SelectMode) -> Self", role: "builder", summary: "" },
            ApiFn { name: "style", signature: "pub fn style(mut self, style: Style) -> Self", role: "builder", summary: "" },
            ApiFn { name: "highlight_style", signature: "pub fn highlight_style(mut self, style: Style) -> Self", role: "builder", summary: "" },
            ApiFn { name: "markers", signature: "pub fn markers(mut self, selected: &'static str, unselected: &'static str) -> Self", role: "builder", summary: "" },
        ],
    },
    ApiType {
        name: "SelectListState",
        module: "hawktui::widget::select_list",
        kind: ApiKind::Struct,
        summary: "State for a [`SelectList`].",
        variants: &[],
        functions: &[
            ApiFn { name: "new", signature: "pub fn new() -> Self", role: "constructor", summary: "" },
            ApiFn { name: "move_up", signature: "pub fn move_up(&mut self, visible_count: usize)", role: "method", summary: "Move cursor up within the visible item count." },
            ApiFn { name: "move_down", signature: "pub fn move_down(&mut self, visible_count: usize)", role: "method", summary: "Move cursor down within the visible item count." },
            ApiFn { name: "toggle_select", signature: "pub fn toggle_select(&mut self, original_idx: usize, mode: SelectMode)", role: "method", summary: "Toggle selection of the item at the given original index." },
            ApiFn { name: "selected_indices", signature: "pub fn selected_indices(&self) -> &[usize]", role: "method", summary: "Returns the selected indices." },
        ],
    },
    ApiType {
        name: "SelectMode",
        module: "hawktui::widget::select_list",
        kind: ApiKind::Enum,
        summary: "Selection mode for the list.",
        variants: &["Single", "Multi"],
        functions: &[
        ],
    },
    ApiType {
        name: "Setting",
        module: "hawktui::widget::settings_list",
        kind: ApiKind::Struct,
        summary: "A single setting entry with a label, a set of possible values, and",
        variants: &[],
        functions: &[
            ApiFn { name: "new", signature: "pub fn new(label: impl Into<String>, values: impl Into<Vec<String>>) -> Self", role: "constructor", summary: "" },
            ApiFn { name: "selected", signature: "pub fn selected(mut self, index: usize) -> Self", role: "builder", summary: "" },
            ApiFn { name: "description", signature: "pub fn description(mut self, desc: impl Into<String>) -> Self", role: "builder", summary: "" },
            ApiFn { name: "current_value", signature: "pub fn current_value(&self) -> &str", role: "method", summary: "Get the currently selected value." },
            ApiFn { name: "cycle_next", signature: "pub fn cycle_next(&mut self)", role: "method", summary: "Cycle to the next value." },
            ApiFn { name: "cycle_prev", signature: "pub fn cycle_prev(&mut self)", role: "method", summary: "Cycle to the previous value." },
        ],
    },
    ApiType {
        name: "SettingsList",
        module: "hawktui::widget::settings_list",
        kind: ApiKind::StatefulWidget { state: "SettingsListState" },
        summary: "An interactive settings list widget displaying key-value pairs with",
        variants: &[],
        functions: &[
            ApiFn { name: "new", signature: "pub fn new(settings: impl Into<Vec<Setting>>) -> Self", role: "constructor", summary: "" },
            ApiFn { name: "block", signature: "pub fn block(mut self, block: Block) -> Self", role: "builder", summary: "" },
            ApiFn { name: "style", signature: "pub fn style(mut self, style: Style) -> Self", role: "builder", summary: "" },
            ApiFn { name: "cursor_style", signature: "pub fn cursor_style(mut self, style: Style) -> Self", role: "builder", summary: "" },
            ApiFn { name: "label_style", signature: "pub fn label_style(mut self, style: Style) -> Self", role: "builder", summary: "" },
            ApiFn { name: "value_style", signature: "pub fn value_style(mut self, style: Style) -> Self", role: "builder", summary: "" },
            ApiFn { name: "description_style", signature: "pub fn description_style(mut self, style: Style) -> Self", role: "builder", summary: "" },
            ApiFn { name: "cursor_symbol", signature: "pub fn cursor_symbol(mut self, symbol: impl Into<String>) -> Self", role: "builder", summary: "" },
            ApiFn { name: "value_separator", signature: "pub fn value_separator(mut self, sep: impl Into<String>) -> Self", role: "builder", summary: "" },
            ApiFn { name: "settings", signature: "pub fn settings(&self) -> &[Setting]", role: "method", summary: "Get a reference to the settings." },
            ApiFn { name: "settings_mut", signature: "pub fn settings_mut(&mut self) -> &mut [Setting]", role: "method", summary: "Get a mutable reference to the settings." },
        ],
    },
    ApiType {
        name: "SettingsListState",
        module: "hawktui::widget::settings_list",
        kind: ApiKind::Struct,
        summary: "State for the settings list (tracks cursor position and scroll offset).",
        variants: &[],
        functions: &[
            ApiFn { name: "new", signature: "pub fn new() -> Self", role: "constructor", summary: "" },
            ApiFn { name: "move_up", signature: "pub fn move_up(&mut self)", role: "method", summary: "" },
            ApiFn { name: "move_down", signature: "pub fn move_down(&mut self, item_count: usize)", role: "method", summary: "" },
        ],
    },
    ApiType {
        name: "Shape",
        module: "hawktui::widget::canvas",
        kind: ApiKind::Trait,
        summary: "Something that can be drawn on a [`Canvas`].",
        variants: &[],
        functions: &[
            ApiFn { name: "draw", signature: "fn draw(&self, painter: &mut Painter)", role: "required", summary: "" },
        ],
    },
    ApiType {
        name: "Span",
        module: "hawktui::core",
        kind: ApiKind::Struct,
        summary: "A styled segment of text (a single style applied to a string).",
        variants: &[],
        functions: &[
            ApiFn { name: "raw", signature: "pub fn raw(content: impl Into<Cow<'static, str>>) -> Self", role: "constructor", summary: "" },
            ApiFn { name: "styled", signature: "pub fn styled(content: impl Into<Cow<'static, str>>, style: Style) -> Self", role: "constructor", summary: "" },
            ApiFn { name: "width", signature: "pub fn width(&self) -> usize", role: "method", summary: "" },
        ],
    },
    ApiType {
        name: "Sparkline",
        module: "hawktui::widget::sparkline",
        kind: ApiKind::Widget,
        summary: "A mini chart showing a data trend as vertical bars.",
        variants: &[],
        functions: &[
            ApiFn { name: "new", signature: "pub fn new(data: impl Into<Vec<u64>>) -> Self", role: "constructor", summary: "" },
            ApiFn { name: "direction", signature: "pub fn direction(mut self, direction: SparklineDirection) -> Self", role: "builder", summary: "Choose which end holds the newest sample." },
            ApiFn { name: "block", signature: "pub fn block(mut self, block: Block) -> Self", role: "builder", summary: "" },
            ApiFn { name: "style", signature: "pub fn style(mut self, style: Style) -> Self", role: "builder", summary: "" },
            ApiFn { name: "bar_style", signature: "pub fn bar_style(mut self, style: Style) -> Self", role: "builder", summary: "" },
            ApiFn { name: "max", signature: "pub fn max(mut self, max: u64) -> Self", role: "builder", summary: "Manually set the maximum value. If `None`, auto-detects from data." },
        ],
    },
    ApiType {
        name: "SparklineDirection",
        module: "hawktui::widget::sparkline",
        kind: ApiKind::Enum,
        summary: "Which end of the sparkline the newest sample sits at.",
        variants: &["LeftToRight", "RightToLeft"],
        functions: &[
        ],
    },
    ApiType {
        name: "SpinnerStyle",
        module: "hawktui::widget::loader",
        kind: ApiKind::Enum,
        summary: "Spinner style presets.",
        variants: &["Braille", "Line", "Dots", "Arc"],
        functions: &[
            ApiFn { name: "frames", signature: "pub fn frames(self) -> &'static [char]", role: "builder", summary: "" },
        ],
    },
    ApiType {
        name: "Style",
        module: "hawktui::core",
        kind: ApiKind::Struct,
        summary: "Complete styling specification for a terminal cell.",
        variants: &[],
        functions: &[
            ApiFn { name: "patch", signature: "pub fn patch(mut self, other: Style) -> Self", role: "builder", summary: "Merge another style on top of this one." },
        ],
    },
    ApiType {
        name: "Stylize",
        module: "hawktui::core",
        kind: ApiKind::Trait,
        summary: "[Stylize] trait enables a fluent shorthand API.",
        variants: &[],
        functions: &[
            ApiFn { name: "style", signature: "fn style(self, style: Style) -> Self", role: "required", summary: "" },
            ApiFn { name: "red", signature: "fn red(self) -> Self", role: "provided", summary: "" },
            ApiFn { name: "green", signature: "fn green(self) -> Self", role: "provided", summary: "" },
            ApiFn { name: "yellow", signature: "fn yellow(self) -> Self", role: "provided", summary: "" },
            ApiFn { name: "blue", signature: "fn blue(self) -> Self", role: "provided", summary: "" },
            ApiFn { name: "magenta", signature: "fn magenta(self) -> Self", role: "provided", summary: "" },
            ApiFn { name: "cyan", signature: "fn cyan(self) -> Self", role: "provided", summary: "" },
            ApiFn { name: "white", signature: "fn white(self) -> Self", role: "provided", summary: "" },
            ApiFn { name: "gray", signature: "fn gray(self) -> Self", role: "provided", summary: "" },
            ApiFn { name: "on_red", signature: "fn on_red(self) -> Self", role: "provided", summary: "" },
            ApiFn { name: "on_green", signature: "fn on_green(self) -> Self", role: "provided", summary: "" },
            ApiFn { name: "on_yellow", signature: "fn on_yellow(self) -> Self", role: "provided", summary: "" },
            ApiFn { name: "on_blue", signature: "fn on_blue(self) -> Self", role: "provided", summary: "" },
            ApiFn { name: "on_magenta", signature: "fn on_magenta(self) -> Self", role: "provided", summary: "" },
            ApiFn { name: "on_cyan", signature: "fn on_cyan(self) -> Self", role: "provided", summary: "" },
            ApiFn { name: "on_white", signature: "fn on_white(self) -> Self", role: "provided", summary: "" },
            ApiFn { name: "bold", signature: "fn bold(self) -> Self", role: "provided", summary: "" },
            ApiFn { name: "dim", signature: "fn dim(self) -> Self", role: "provided", summary: "" },
            ApiFn { name: "italic", signature: "fn italic(self) -> Self", role: "provided", summary: "" },
            ApiFn { name: "underlined", signature: "fn underlined(self) -> Self", role: "provided", summary: "" },
            ApiFn { name: "reversed", signature: "fn reversed(self) -> Self", role: "provided", summary: "" },
            ApiFn { name: "crossed_out", signature: "fn crossed_out(self) -> Self", role: "provided", summary: "" },
        ],
    },
    ApiType {
        name: "Symbol",
        module: "hawktui::core",
        kind: ApiKind::Struct,
        summary: "A grapheme cluster stored in 8 bytes.",
        variants: &[],
        functions: &[
            ApiFn { name: "new", signature: "pub fn new(s: &str) -> Self", role: "constructor", summary: "Store a grapheme cluster, interning it if it exceeds the inline capacity." },
            ApiFn { name: "from_char", signature: "pub fn from_char(ch: char) -> Self", role: "constructor", summary: "Store a single `char` — always inline, never allocates." },
            ApiFn { name: "as_str", signature: "pub fn as_str(&self) -> &str", role: "method", summary: "The cluster as a string slice." },
            ApiFn { name: "is_empty", signature: "pub fn is_empty(&self) -> bool", role: "method", summary: "Whether this symbol holds no content (a wide-grapheme continuation cell)." },
            ApiFn { name: "len", signature: "pub fn len(&self) -> usize", role: "method", summary: "Length of the cluster in bytes." },
        ],
    },
    ApiType {
        name: "Table",
        module: "hawktui::widget::table",
        kind: ApiKind::StatefulWidget { state: "TableState" },
        summary: "A data table widget with column headers and row selection.",
        variants: &[],
        functions: &[
            ApiFn { name: "new", signature: "pub fn new( columns: impl IntoIterator<Item = TableColumn>, rows: impl IntoIterator<Item = TableRow>, ) -> Self", role: "constructor", summary: "" },
            ApiFn { name: "block", signature: "pub fn block(mut self, block: Block) -> Self", role: "builder", summary: "" },
            ApiFn { name: "style", signature: "pub fn style(mut self, style: Style) -> Self", role: "builder", summary: "" },
            ApiFn { name: "header_style", signature: "pub fn header_style(mut self, style: Style) -> Self", role: "builder", summary: "" },
            ApiFn { name: "highlight_style", signature: "pub fn highlight_style(mut self, style: Style) -> Self", role: "builder", summary: "" },
            ApiFn { name: "column_spacing", signature: "pub fn column_spacing(mut self, spacing: u16) -> Self", role: "builder", summary: "" },
        ],
    },
    ApiType {
        name: "TableColumn",
        module: "hawktui::widget::table",
        kind: ApiKind::Struct,
        summary: "A column definition for a [`Table`].",
        variants: &[],
        functions: &[
            ApiFn { name: "new", signature: "pub fn new(header: impl Into<Line>, width: TableColumnWidth) -> Self", role: "constructor", summary: "" },
        ],
    },
    ApiType {
        name: "TableColumnWidth",
        module: "hawktui::widget::table",
        kind: ApiKind::Enum,
        summary: "Constraint for a table column width.",
        variants: &["Fixed", "Percent", "Fill"],
        functions: &[
        ],
    },
    ApiType {
        name: "TableRow",
        module: "hawktui::widget::table",
        kind: ApiKind::Struct,
        summary: "A single row in a [`Table`].",
        variants: &[],
        functions: &[
            ApiFn { name: "new", signature: "pub fn new(cells: impl IntoIterator<Item = impl Into<Line>>) -> Self", role: "constructor", summary: "" },
            ApiFn { name: "style", signature: "pub fn style(mut self, style: Style) -> Self", role: "builder", summary: "" },
            ApiFn { name: "height", signature: "pub fn height(mut self, height: u16) -> Self", role: "builder", summary: "" },
        ],
    },
    ApiType {
        name: "TableState",
        module: "hawktui::widget::table",
        kind: ApiKind::Struct,
        summary: "Table state for scrolling and selection.",
        variants: &[],
        functions: &[
            ApiFn { name: "new", signature: "pub fn new() -> Self", role: "constructor", summary: "" },
            ApiFn { name: "select", signature: "pub fn select(&mut self, index: Option<usize>)", role: "method", summary: "" },
            ApiFn { name: "select_next", signature: "pub fn select_next(&mut self, row_count: usize)", role: "method", summary: "" },
            ApiFn { name: "select_previous", signature: "pub fn select_previous(&mut self)", role: "method", summary: "" },
        ],
    },
    ApiType {
        name: "Tabs",
        module: "hawktui::widget::tabs",
        kind: ApiKind::Widget,
        summary: "A tab bar widget for section navigation.",
        variants: &[],
        functions: &[
            ApiFn { name: "new", signature: "pub fn new(titles: impl IntoIterator<Item = impl Into<Line>>) -> Self", role: "constructor", summary: "" },
            ApiFn { name: "block", signature: "pub fn block(mut self, block: Block) -> Self", role: "builder", summary: "" },
            ApiFn { name: "select", signature: "pub fn select(mut self, selected: usize) -> Self", role: "builder", summary: "" },
            ApiFn { name: "style", signature: "pub fn style(mut self, style: Style) -> Self", role: "builder", summary: "" },
            ApiFn { name: "highlight_style", signature: "pub fn highlight_style(mut self, style: Style) -> Self", role: "builder", summary: "" },
            ApiFn { name: "divider", signature: "pub fn divider(mut self, divider: impl Into<Span>) -> Self", role: "builder", summary: "" },
            ApiFn { name: "padding", signature: "pub fn padding(mut self, left: impl Into<Span>, right: impl Into<Span>) -> Self", role: "builder", summary: "" },
        ],
    },
    ApiType {
        name: "Terminal",
        module: "hawktui::terminal",
        kind: ApiKind::Struct,
        summary: "Manages the terminal lifecycle and double-buffered rendering.",
        variants: &[],
        functions: &[
            ApiFn { name: "new", signature: "pub fn new(backend: B) -> io::Result<Self>", role: "constructor", summary: "Create a new terminal backed by the given backend." },
            ApiFn { name: "backend", signature: "pub fn backend(&self) -> &B", role: "method", summary: "Get a reference to the backend." },
            ApiFn { name: "backend_mut", signature: "pub fn backend_mut(&mut self) -> &mut B", role: "method", summary: "Get a mutable reference to the backend." },
            ApiFn { name: "area", signature: "pub fn area(&self) -> Rect", role: "method", summary: "Get the current viewport area." },
            ApiFn { name: "hit_map", signature: "pub fn hit_map(&self) -> &HitMap", role: "method", summary: "Get the hit map (for mouse event resolution)." },
            ApiFn { name: "init", signature: "pub fn init(&mut self) -> io::Result<()>", role: "method", summary: "Initialize the terminal (alternate screen, raw mode, mouse, hide cursor)." },
            ApiFn { name: "restore", signature: "pub fn restore(&mut self) -> io::Result<()>", role: "method", summary: "Restore the terminal to its original state." },
            ApiFn { name: "autoresize", signature: "pub fn autoresize(&mut self) -> io::Result<()>", role: "method", summary: "Automatically detect and apply the current terminal size." },
        ],
    },
    ApiType {
        name: "TestBackend",
        module: "hawktui::backend",
        kind: ApiKind::Struct,
        summary: "In-memory backend for testing.",
        variants: &[],
        functions: &[
            ApiFn { name: "new", signature: "pub fn new(width: u16, height: u16) -> Self", role: "constructor", summary: "" },
            ApiFn { name: "buffer", signature: "pub fn buffer(&self) -> &Buffer", role: "method", summary: "Get the current buffer contents (for test assertions)." },
            ApiFn { name: "row_text", signature: "pub fn row_text(&self, y: u16) -> String", role: "method", summary: "Get the text content at a specific row, with trailing spaces removed." },
            ApiFn { name: "to_text", signature: "pub fn to_text(&self) -> String", role: "method", summary: "The whole screen as plain text, one line per row, joined by `\\n`." },
        ],
    },
    ApiType {
        name: "Text",
        module: "hawktui::core",
        kind: ApiKind::Struct,
        summary: "Multi-line styled text.",
        variants: &[],
        functions: &[
            ApiFn { name: "raw", signature: "pub fn raw(content: impl Into<Cow<'static, str>>) -> Self", role: "constructor", summary: "" },
            ApiFn { name: "styled", signature: "pub fn styled(content: impl Into<Cow<'static, str>>, style: Style) -> Self", role: "constructor", summary: "" },
            ApiFn { name: "alignment", signature: "pub fn alignment(mut self, alignment: Alignment) -> Self", role: "builder", summary: "" },
            ApiFn { name: "height", signature: "pub fn height(&self) -> usize", role: "method", summary: "Total number of lines." },
            ApiFn { name: "width", signature: "pub fn width(&self) -> usize", role: "method", summary: "Width of the widest line." },
        ],
    },
    ApiType {
        name: "Wrap",
        module: "hawktui::widget::paragraph",
        kind: ApiKind::Enum,
        summary: "Word-wrap mode for paragraph text.",
        variants: &["None", "Word", "Char"],
        functions: &[
        ],
    },
];

/// Everything `use hawktui::prelude::*` brings into scope (31 items).
pub static PRELUDE: &[&str] = &[
    "Alignment",
    "Animation",
    "Backend",
    "Buffer",
    "Cell",
    "Color",
    "Constraint",
    "CrosstermBackend",
    "Direction",
    "Easing",
    "Error",
    "Event",
    "Flex",
    "KeyCode",
    "KeyEvent",
    "KeyModifiers",
    "Layout",
    "Line",
    "Margin",
    "Modifier",
    "MouseButton",
    "MouseEvent",
    "Rect",
    "Result",
    "Span",
    "Spring",
    "Style",
    "Stylize",
    "Text",
    "Timeline",
    "Tween",
];
